(function(){"use strict";var _get=function get(object,property,receiver){if(object===null)object=Function.prototype;var desc=Object.getOwnPropertyDescriptor(object,property);if(desc===undefined){var parent=Object.getPrototypeOf(object);if(parent===null){return undefined}else{return get(parent,property,receiver)}}else if("value"in desc){return desc.value}else{var getter=desc.get;if(getter===undefined){return undefined}return getter.call(receiver)}};var _createClass=function(){function defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if("value"in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor)}}return function(Constructor,protoProps,staticProps){if(protoProps)defineProperties(Constructor.prototype,protoProps);if(staticProps)defineProperties(Constructor,staticProps);return Constructor}}();function _possibleConstructorReturn(self,call){if(!self){throw new ReferenceError("this hasn't been initialised - super() hasn't been called")}return call&&(typeof call==="object"||typeof call==="function")?call:self}function _inherits(subClass,superClass){if(typeof superClass!=="function"&&superClass!==null){throw new TypeError("Super expression must either be null or a function, not "+typeof superClass)}subClass.prototype=Object.create(superClass&&superClass.prototype,{constructor:{value:subClass,enumerable:false,writable:true,configurable:true}});if(superClass)Object.setPrototypeOf?Object.setPrototypeOf(subClass,superClass):subClass.__proto__=superClass}function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError("Cannot call a class as a function")}}/*
    A 3d coordinate class
    Author: Tar van Krieken
    Starting Date: 28/04/2018
*/var getXYZ=function getXYZ(x,y,z){if(x.x!=null||x.y!=null||x.z!=null){return{x:x.x||0,y:x.y||0,z:x.z||0}}if(x.x!=null||x.y!=null||x.z!=null){return{x:x.x||0,y:x.y||0,z:x.z||0}}if(x!==undefined&&y===undefined&&z===undefined){return{x:x,y:x,z:x}}return{x:x||0,y:y||0,z:z||0}};var XYZ=function(){function XYZ(x,y,z){_classCallCheck(this,XYZ);this.l=[];//change listeners
this.set(x||0,y,z)}//listeners
_createClass(XYZ,[{key:"onChange",value:function onChange(func){this.l.push(func);return this}},{key:"offChange",value:function offChange(func){var index=this.l.indexOf(func);if(index!=-1)this.l.splice(index,1);return this}},{key:"__fireEvent",value:function __fireEvent(old){for(var i=0;i<this.l.length;i++){//notify all listeners
this.l[i].call(this,this,old||this)}}//set
},{key:"set",value:function set(x,y,z){var old={x:this.x,y:this.y,z:this.z};var xyz=getXYZ(x,y,z);this.x=xyz.x;this.y=xyz.y;this.z=xyz.z;this.__fireEvent(old);return this}},{key:"setX",value:function setX(x){return this.set(x,this.y,this.z)}},{key:"getX",value:function getX(){return this.x}},{key:"setY",value:function setY(y){return this.set(this.x,y,this.z)}},{key:"getY",value:function getY(){return this.y}},{key:"setZ",value:function setZ(z){return this.set(this.x,this.y,z)}},{key:"getZ",value:function getZ(){return this.z}//alter
},{key:"add",value:function add(x,y,z){var xyz=getXYZ(x,y,z);return this.set(this.x+xyz.x,this.y+xyz.y,this.z+xyz.z)}},{key:"sub",value:function sub(x,y,z){var xyz=getXYZ(x,y,z);return this.set(this.x-xyz.x,this.y-xyz.y,this.z-xyz.z)}},{key:"mul",value:function mul(x,y,z){var xyz=getXYZ(x,y,z);return this.set(this.x*xyz.x,this.y*xyz.y,this.z*xyz.z)}},{key:"div",value:function div(x,y,z){var xyz=getXYZ(x,y,z);return this.set(this.x/xyz.x,this.y/xyz.y,this.z/xyz.z)}},{key:"mod",value:function mod(x,y,z){var xyz=getXYZ(x,y,z);return this.set(xyz.x==0?this.x:this.x%xyz.x,xyz.y==0?this.y:this.y%xyz.y,xyz.z==0?this.z:this.z%xyz.z)}//compare method
},{key:"equals",value:function equals(x,y,z){var xyz=getXYZ(x,y,z);return xyz.x==this.x&&xyz.y==this.y&&xyz.z==this.z}//create
},{key:"getVecTo",value:function getVecTo(x,y,z){return new Vec(x,y,z).sub(this)}}]);return XYZ}();/*
    A 3d vector class
    Author: Tar van Krieken
    Starting Date: 30/04/2018
*/var getXYZ=function getXYZ(x,y,z){if(x.x!=null||x.y!=null||x.z!=null){return{x:x.x||0,y:x.y||0,z:x.z||0}}if(x.x!=null||x.y!=null||x.z!=null){return{x:x.x||0,y:x.y||0,z:x.z||0}}if(x!==undefined&&y===undefined&&z===undefined){return{x:x,y:x,z:x}}return{x:x||0,y:y||0,z:z||0}};var Vec=function(_XYZ){_inherits(Vec,_XYZ);function Vec(x,y,z){_classCallCheck(this,Vec);return _possibleConstructorReturn(this,(Vec.__proto__||Object.getPrototypeOf(Vec)).call(this,x,y,z))}//check if it is non zero
_createClass(Vec,[{key:"isNonZero",value:function isNonZero(modifier){modifier=modifier||1;return Math.abs(this.x)>1e-3*modifier||Math.abs(this.y)>1e-3*modifier||Math.abs(this.z)>1e-3*modifier}//angles (for 2d)
},{key:"setAngle",value:function setAngle(angle){var zAxisDist=Math.sqrt(this.x*this.x+this.y*this.y);var p=Math.atan2(this.z,zAxisDist);var length=this.getLength();return this.set(Math.cos(angle)*Math.cos(p)*length,Math.sin(angle)*Math.cos(p)*length,Math.sin(p)*length)}},{key:"getAngle",value:function getAngle(){return Math.atan2(this.y,this.x)}},{key:"addAngle",value:function addAngle(angle){return this.setAngle(this.getAngle()+angle)}//set angles
},{key:"setPYL",value:function setPYL(pitch,yaw,length){return this.set(Math.cos(yaw)*Math.cos(pitch)*length,Math.sin(pitch)*length,-Math.sin(yaw)*Math.cos(pitch)*length)}//yaw
},{key:"setYaw",value:function setYaw(yaw){var pitch=this.getPitch();var length=this.getLength();return this.setPYL(pitch,yaw,length)}},{key:"getYaw",value:function getYaw(){return Math.atan2(-this.z,this.x)}},{key:"addYaw",value:function addYaw(yaw){return this.setYaw(this.getYaw()+yaw)}//pitch
},{key:"setPitch",value:function setPitch(pitch){var yaw=this.getYaw();var length=this.getLength();return this.setPYL(pitch,yaw,length)}},{key:"getPitch",value:function getPitch(){var yAxisDist=Math.sqrt(this.x*this.x+this.z*this.z);return Math.atan2(this.y,yAxisDist)}},{key:"addPitch",value:function addPitch(pitch){return this.setPitch(this.getPitch()+pitch)}//length
},{key:"setLength",value:function setLength(length){return this.mul(length/this.getLength())}},{key:"getLength",value:function getLength(){return Math.sqrt(this.x*this.x+this.y*this.y+this.z*this.z)}},{key:"addLength",value:function addLength(length){return this.setLength(this.getLength()+length)}},{key:"subLength",value:function subLength(length){return this.setLength(Math.max(0,this.getLength()-length))}//rotate around rotation vector
},{key:"rotate",value:function rotate(x,y,z){var XYZ=getXYZ(x,y,z);this.addYaw(XYZ.y);this.addPitch(XYZ.z);return this}//translate to shape rotation
},{key:"getRot",value:function getRot(){return new Vec(0,this.getYaw(),this.getPitch())}},{key:"getLookAt",value:function getLookAt(){return new Vec(1,0,0).setPitch(this.getZ()).setYaw(this.getY())}}]);return Vec}(XYZ);/*
    Options class to indicate what options a visualisation has
    Author: Tar van Krieken
    Starting Date: 08/05/2018
*/var Options=function(){function Options(){_classCallCheck(this,Options);this.options={};//All the values of the options
this.optionsChangeListeners=[];//Listeners to check whenever a option got created or removed
this.optionListeners={};//Listeners to check whenever the value of an option has changed
}//getters and setters
_createClass(Options,[{key:"setOption",value:function setOption(option,value){var option=this.getOptionData(option);var oldValue=option.value;option.value=value;this.__updateOptionValue(option.name,oldValue)}},{key:"getOptionData",value:function getOptionData(option){return this.options[option]}},{key:"getOption",value:function getOption(option){return this.options[option].value}//option creation/removal
},{key:"createOption",value:function createOption(name,type,initValue){if(!this.options[name]){this.options[name]={name:name,type:type,value:initValue};this.optionListeners[name]=[];this.__updateOptions("create",this.options[name])}return this}},{key:"deleteOption",value:function deleteOption(name){var option=this.options[name];if(option){delete this.options[name];this.__updateOptions("delete",option)}return this}//event listener invokes
},{key:"__updateOptionValue",value:function __updateOptionValue(option,oldValue){var listeners=this.optionListeners[option];for(var i=0;i<listeners.length;i++){var l=listeners[i];l.call(this,this.options[option].value,oldValue)}return this}},{key:"__updateOptions",value:function __updateOptions(eventType,option){for(var i=0;i<this.optionsChangeListeners.length;i++){var l=this.optionsChangeListeners[i];l.call(this,eventType,option)}return this}//register listeners
},{key:"onOptionsChange",value:function onOptionsChange(listener){var index=this.optionsChangeListeners.indexOf(listener);if(index==-1)this.optionsChangeListeners.push(listener);return this}},{key:"offOptionsChange",value:function offOptionsChange(listener){var index=this.optionsChangeListeners.indexOf(listener);if(index!=-1)this.optionsChangeListeners.splice(index,1);return this}},{key:"onOptionChange",value:function onOptionChange(option,listener){var l=this.optionListeners[option];var index=l.indexOf(listener);if(index==-1)l.push(listener);return this}},{key:"offOptionChange",value:function offOptionChange(option,listener){var l=this.optionListeners[option];var index=l.indexOf(listener);if(index!=-1)l.splice(index,1);return this}}]);return Options}();window.Options=Options;/*
    Generalized graphics abstract class
    Author: Tar van Krieken
    Starting Date: 28/04/2018
*/var AbstractCamera=function(){function AbstractCamera(graphics){_classCallCheck(this,AbstractCamera);this.graphics=graphics;this.loc=new XYZ(0,0,0);this.rot=new Vec(0,0,0);this.velo=new Vec(0,0,0);this.rotVelo=new Vec(0,0,0);this.scale=1;this.scaleVelo=0;this.target={};//some constants to alter the targetting system
this.speed={scale:600,rot:600,loc:600};this.targetForce={scale:2,rot:3,loc:3};this.targetFriction={scale:0.8,rot:0.8,loc:0.8};this.targetFullRotations=false;//location and rotation change
var This=this;this.loc.onChange(function(){This.graphics.__updateHtmlShapesLoc()});this.rot.onChange(function(){This.graphics.__updateHtmlShapesLoc()});var This=this;graphics.onUpdate(function(time){//move to target pos if defined
if(This.target.loc){var delta=This.loc.getVecTo(This.target.loc);This.velo.add(delta.mul(time*This.targetForce.loc))}//move to target pos if defined
if(This.target.rot){var delta=This.rot.getVecTo(This.target.rot);if(!this.targetFullRotations)//modulo centered around 0
delta.mod(Math.PI*2).add(Math.PI*3).mod(Math.PI*2).sub(Math.PI);This.rotVelo.add(delta.mul(time*This.targetForce.rot))}//move to target pos if defined
if(This.target.scale){var delta=This.target.scale-This.scale;This.scaleVelo+=delta*time*This.targetForce.scale}//apply velocity
This.velo.mul(1-This.targetFriction.loc);//drag/friction
This.rotVelo.mul(1-This.targetFriction.rot);This.scaleVelo*=1-This.targetFriction.scale;This.loc.add(new Vec(This.velo).mul(time*This.speed.loc));This.rot.add(new Vec(This.rotVelo).mul(time*This.speed.rot));This.setScale(This.scale+This.scaleVelo*time*This.speed.scale)})}_createClass(AbstractCamera,[{key:"__updateLoc",value:function __updateLoc(){}//position
},{key:"setX",value:function setX(x){this.loc.setX(x);return this}},{key:"getX",value:function getX(){return this.loc.getX()}},{key:"setY",value:function setY(y){this.loc.setY(y);return this}},{key:"getY",value:function getY(){return this.loc.getY()}},{key:"setZ",value:function setZ(z){this.loc.setZ(z);return this}},{key:"getZ",value:function getZ(){return this.loc.getZ()}},{key:"setLoc",value:function setLoc(x,y,z){this.loc.set(x,y,z);return this}},{key:"getLoc",value:function getLoc(){return this.loc}//rotation
},{key:"setXRot",value:function setXRot(x){this.rot.setX(x);return this}},{key:"getXRot",value:function getXRot(){return this.rot.getX()}},{key:"setYRot",value:function setYRot(y){this.rot.setY(y);return this}},{key:"getYRot",value:function getYRot(){return this.rot.getY()}},{key:"setZRot",value:function setZRot(z){this.rot.setZ(z);return this}},{key:"getZRot",value:function getZRot(){return this.rot.getZ()}},{key:"setRot",value:function setRot(x,y,z){this.rot.set(x,y,z);return this}},{key:"getRot",value:function getRot(){return this.rot}//scaling
},{key:"setScale",value:function setScale(scale){this.scale=scale;this.graphics.__updateHtmlShapesLoc();return this}},{key:"getScale",value:function getScale(){return this.scale}//velocity
},{key:"getVelo",value:function getVelo(){return this.velo}},{key:"getRotVelo",value:function getRotVelo(){return this.rotVelo()}},{key:"setScaleVelo",value:function setScaleVelo(scaleVelo){this.scaleVelo=scaleVelo;return this}},{key:"getScaleVelo",value:function getScaleVelo(){return this.scaleVelo}//targetting methods
},{key:"setTargetLoc",value:function setTargetLoc(x,y,z){if(x instanceof AbstractShape)x=x.getLoc();if(x.x==null)x=new XYZ(x,y,z);this.target.loc=x;return this}},{key:"setTargetRot",value:function setTargetRot(x,y,z){if(x instanceof AbstractShape)x=x.getRot();if(x.x==null)x=new XYZ(x,y,z);this.target.rot=x;return this}},{key:"setTargetScale",value:function setTargetScale(scale){if(scale instanceof AbstractShape)scale=1/scale.getScale();this.target.scale=scale;return this}},{key:"setTarget",value:function setTarget(loc,rot,scale){this.setTargetLoc(loc);this.setTargetRot(rot);this.setTargetScale(scale);return this}},{key:"setTargetFullRotations",value:function setTargetFullRotations(rotations){this.targetFullRotations=rotations;return this}},{key:"getTargetFullRotations",value:function getTargetFullRotations(){return this.targetFullRotations}//mouse interaction
},{key:"translateScreenToWorldLoc",value:function translateScreenToWorldLoc(x,y,z){}},{key:"translateWorldToScreenLoc",value:function translateWorldToScreenLoc(x,y,z){}}]);return AbstractCamera}();/*
    Generalized graphics abstract class
    Author: Tar van Krieken
    Starting Date: 28/04/2018
*/var AbstractGraphics=function(){function AbstractGraphics(width,height,container,preInit){_classCallCheck(this,AbstractGraphics);if(preInit instanceof Function)preInit.call(this);this.updateListeners=[];this.background=0;//if no height and width is defined, use size of container instead
if(!height){if(!width)width=$("body");if(!container)container=width;width=$(container).width();height=$(container).height()}this.size={width:width,height:height};if(!container)container=$("body");this.container=$(container);//event listeners
this.listeners={mouseClick:[],mousePress:[],mouseScroll:[],mouseMove:[],keyPress:[]};this.DOMEventListeners={//tracked for when destroying the graphics
};this.pressedKeys={};//shape data storage
this.shapes={visible:[],//all shapes that are rendered
alive:[],//shapes that are visible, and aren't in the process of being deleted
active:[],//shapes that receive update events
html:[]//html shapes that aren't part of pixi
};this.maxNodeCount=12;//the max number of nodes that can be visible at any point
this.spatialTree=new rbush3d(16,[".aabb.minX",".aabb.minY",".aabb.minZ",".aabb.maxX",".aabb.maxY",".aabb.maxZ"]);;//create an UID to be used when searching for shapes in the tree
this.UID=Math.floor(Math.random()*Math.pow(10,10));if(window.debugging)this.__setupFpsCounter()}_createClass(AbstractGraphics,[{key:"getCamera",value:function getCamera(){return this.camera}},{key:"getSpatialTree",value:function getSpatialTree(){return this.spatialTree}},{key:"getUID",value:function getUID(){return this.UID}},{key:"__setupFpsCounter",value:function __setupFpsCounter(){var stats=this.stats=new Stats;this.stats.showPanel(0);// 0: fps, 1: ms, 2: mb, 3+: custom
this.getContainer().append(stats.domElement);$(stats.domElement).css("position","absolute")}//tree search
},{key:"search",value:function search(loc,radius,filter){var tree=this.getSpatialTree();if(tree){//search the tree
var results=tree.search({minX:loc.getX()-radius,minY:loc.getY()-radius,minZ:loc.getZ()-radius,maxX:loc.getX()+radius,maxY:loc.getY()+radius,maxZ:loc.getZ()+radius});if(filter)//apply the filter and make sure to not include 'this'
return results.filter(filter);return results}return[]}//start/stop rendering
},{key:"pause",value:function pause(fully){}},{key:"start",value:function start(){}},{key:"destroy",value:function destroy(){//dispose the graphics completely
for(var i=this.shapes.html.length-1;i>=0;i--){this.shapes.html[i].remove()}}//just retrieve some container info
},{key:"getWidth",value:function getWidth(canvas){if(canvas)//tthe actual width instead of resolution width (should be the same)
return this.getCanvas().width();return this.size.width}},{key:"getHeight",value:function getHeight(canvas){if(canvas)//tthe actual height instead of resolution height (should be the same)
return this.getCanvas().height();return this.size.height}},{key:"getContainer",value:function getContainer(){return this.container}},{key:"getCanvas",value:function getCanvas(){return this.getContainer().find("canvas")}//a method to add an event that fires whenever the screen is rendered
},{key:"onUpdate",value:function onUpdate(listener){var index=this.updateListeners.indexOf(listener);if(index==-1)this.updateListeners.push(listener);return this}},{key:"offUpdate",value:function offUpdate(listener){var index=this.updateListeners.indexOf(listener);if(index!=-1)this.updateListeners.splice(index,1);return this}},{key:"__onUpdate",value:function __onUpdate(delta){if(this.stats)this.stats.begin();//general listeners
for(var i=0;i<this.updateListeners.length;i++){this.updateListeners[i].apply(this,arguments)}//active shape listeners
for(var i=0;i<this.shapes.active.length;i++){this.shapes.active[i].__triggerUpdate(delta)}if(this.stats)this.stats.end();return this}//methods to add and remove shapes from the window
},{key:"add",value:function add(shape){for(var i=0;i<arguments.length;i++){arguments[i].add()}return this}},{key:"remove",value:function remove(shape){for(var i=0;i<arguments.length;i++){arguments[i].remove()}return this}},{key:"addShape",value:function addShape(shape){return this.add.apply(this,arguments)}},{key:"removeShape",value:function removeShape(shape){return this.remove.apply(this,arguments)}},{key:"__registerShape",value:function __registerShape(shape){this.getShapes().push(shape);//add to alive shapes
this.getShapes(true).push(shape);//add to all shapes
}},{key:"__deregisterShape",value:function __deregisterShape(shape,fully){var shapes=this.getShapes();//remove from alive shapes
var index=shapes.indexOf(shape);if(index!=-1)shapes.splice(index,1);if(fully){//remove from all shapes
var shapes=this.getShapes(true);var index=shapes.indexOf(shape);if(index!=-1)shapes.splice(index,1)}}},{key:"getShapes",value:function getShapes(allShapes){//all shapes indicates whether or not to include shapes that have tehnically been deleted, but are still in some deletion animation
if(allShapes)return this.shapes.visible;return this.shapes.alive}//methods to active or deactive shapes (meaning that they will or won't receive update events)
},{key:"activateShape",value:function activateShape(shape){for(var i=0;i<arguments.length;i++){var shape=arguments[i];var index=this.shapes.active.indexOf(shape);if(index==-1)this.shapes.active.push(shape)}return this}},{key:"deactivateShape",value:function deactivateShape(shape){for(var i=0;i<arguments.length;i++){var shape=arguments[i];var index=this.shapes.active.indexOf(shape);if(index!=-1)this.shapes.active.splice(index,1)}return this}//background color
},{key:"setBackground",value:function setBackground(color){this.background=color;return this}},{key:"getBackground",value:function getBackground(){return this.background}//interactions
},{key:"getMouseScreenLoc",value:function getMouseScreenLoc(){}},{key:"getMouseVec",value:function getMouseVec(x,y,z){}},{key:"getMouseLoc",value:function getMouseLoc(){}},{key:"getMousePressed",value:function getMousePressed(){}},{key:"isKeyPressed",value:function isKeyPressed(key){return!!this.pressedKeys[key.toLowerCase()]}//manage html shapes, update their locations
},{key:"getShapesHtml",value:function getShapesHtml(){return this.shapes.html}},{key:"__updateHtmlShapesLoc",value:function __updateHtmlShapesLoc(){for(var i=0;i<this.shapes.html.length;i++){this.shapes.html[i].__updateLoc()}}//event listeners
},{key:"__registerListener",value:function __registerListener(type,listener){if(this.listeners[type].indexOf(listener)==-1)this.listeners[type].push(listener);return this}},{key:"__deregisterListener",value:function __deregisterListener(type,listener){var index=this.listeners[type].indexOf(listener);if(index!=-1)this.listeners[type].splice(index,1);return this}},{key:"__triggerListener",value:function __triggerListener(type){var args=Array.from(arguments);args.shift();var ls=this.listeners[type];for(var i=0;i<ls.length;i++){ls[i].apply(this,args)}return this}},{key:"onClick",value:function onClick(func){return this.__registerListener("mouseClick",func)}},{key:"offClick",value:function offClick(func){return this.__deregisterListener("mouseClick",func)}},{key:"__triggerClick",value:function __triggerClick(event){return this.__triggerListener("mouseClick",event)}},{key:"onMousePress",value:function onMousePress(func){return this.__registerListener("mousePress",func)}},{key:"offMousePress",value:function offMousePress(func){return this.__deregisterListener("mousePress",func)}},{key:"__triggerMousePress",value:function __triggerMousePress(down,event){return this.__triggerListener("mousePress",down,event)}},{key:"onMouseScroll",value:function onMouseScroll(func){return this.__registerListener("mouseScroll",func)}},{key:"offMouseScroll",value:function offMouseScroll(func){return this.__deregisterListener("mouseScroll",func)}},{key:"__triggerMouseScroll",value:function __triggerMouseScroll(amount,event){return this.__triggerListener("mouseScroll",amount,event)}},{key:"onMouseMove",value:function onMouseMove(func){return this.__registerListener("mouseMove",func)}},{key:"offMouseMove",value:function offMouseMove(func){return this.__deregisterListener("mouseMove",func)}},{key:"__triggerMouseMove",value:function __triggerMouseMove(pos,event){return this.__triggerListener("mouseMove",pos,event)}},{key:"onKeyPress",value:function onKeyPress(func){return this.__registerListener("keyPress",func)}},{key:"offKeyPress",value:function offKeyPress(func){return this.__deregisterListener("keyPress",func)}},{key:"__triggerKeyPress",value:function __triggerKeyPress(down,key,event){if(down)this.pressedKeys[key.toLowerCase()]=true;else delete this.pressedKeys[key.toLowerCase()];return this.__triggerListener("keyPress",down,key,event)}}]);return AbstractGraphics}();AbstractGraphics.getDescription=function(){return this.description};AbstractGraphics.description={name:"VIS"+Math.floor(Math.random()*Math.pow(10,6)),description:"",image:""};/*
    Generalized shape abstract class
    Author: Tar van Krieken
    Starting Date: 28/04/2018
*/var AbstractShape=function(){function AbstractShape(graphics,preInit){_classCallCheck(this,AbstractShape);//setup stuff before init
this.storeInSpatialTree=false;if(preInit)preInit.call(this);//set fields
this.graphics=graphics;this.transform={loc:new XYZ(0,0,0),rot:new XYZ(0,0,0),scale:1,scaleListeners:[]};this.velo={loc:new Vec(0,0,0),rot:new Vec(0,0,0),scale:0};this.speedFactor=1;//a constant to multiply the velo with
this.aabb={minX:0,maxX:0,minY:0,maxY:0,minZ:0,maxZ:0};//loose bounding box
this.color=0;//int color
this.isRendered=false;//whether or not the shape is being rendered
this.isRenderedListeners=[];//listeners that check if the shape is rendered
this.isAlive=false;//whether or not the shape is rendered, and not in the process of being removed
//interaction listeners
this.listeners={update:[],mouseClick:[],mouseHover:[],mousePress:[],mouseScroll:[],mouseMove:[],keyPress:[]};//target
this.target={loc:null,rot:null,scale:null,friction:{loc:0.8,rot:0.8,scale:0.7},speed:{loc:1,rot:1,scale:2},callback:{loc:null,rot:null,scale:null}};//whether updates and interactions are disabled
this.updatesDisabled=false;this.interactionsDisabled=false;//add listener to loc changes in order to update aabb
var This=this;this.transform.loc.onChange(function(){This.__updateAABB()});//velo listeners
this.velo.loc.onChange(function(){This.__updateUpdates()});//update AABB
this.__updateAABB()}//build in listeners
_createClass(AbstractShape,[{key:"__onDrag",value:function __onDrag(location){}//method to be overwritten for custom dragging
},{key:"__registerUpdateListener",value:function __registerUpdateListener(){return this.onUpdate(this.__onUpdate)}},{key:"__deregisterUpdateListener",value:function __deregisterUpdateListener(){return this.offUpdate(this.__onUpdate)}},{key:"__onUpdate",value:function __onUpdate(deltaTime){//method to be extended to be called every 'tick'
//apply velocities
var velo=this.getVelo();if(velo.isNonZero(this.getScale()))this.getLoc().add(new Vec(velo).mul(deltaTime*this.speedFactor));var velo=this.getRotVelo();if(velo.isNonZero())this.getRot().add(new Vec(velo).mul(deltaTime*this.speedFactor));var velo=this.getScaleVelo();if(Math.abs(velo)>1e-3*this.getScale())this.setScale(this.getScale()+velo*deltaTime*this.speedFactor);//targetting methods
if(this.target.loc!=null){var delta=this.getVecTo(this.target.loc instanceof Function?this.target.loc.call(this):this.target.loc);var velo=this.getVelo().mul(this.target.friction.loc).add(delta.mul(this.target.speed.loc));if(delta.getLength()<1*this.getScale()&&velo.getLength()<150*this.getScale()&&this.target.callback.loc){this.target.callback.loc.call(this);this.target.callback.loc=null}}if(this.target.rot!=null){var delta=this.getRot().getVecTo(this.target.rot instanceof Function?this.target.rot.call(this):this.target.rot);var velo=this.getRotVelo().mul(this.target.friction.rot).add(delta.mul(this.target.speed.rot));if(delta.getLength()<0.1&&velo.getLength()<0.1&&this.target.callback.rot){this.target.callback.rot.call(this);this.target.callback.rot=null}}if(this.target.scale!=null){var delta=(this.target.scale instanceof Function?this.target.scale.call(this):this.target.scale)-this.getScale();this.setScaleVelo(this.getScaleVelo()*this.target.friction.scale+delta*this.target.speed.scale);if(delta<0.01*Math.max(0.01,this.getScale())&&Math.abs(this.getScaleVelo())<0.05*Math.max(0.01,this.getScale())&&this.target.callback.scale){this.target.callback.scale.call(this);this.target.callback.scale=null}}return this}//position
},{key:"setX",value:function setX(x){this.transform.loc.setX(x);return this}},{key:"getX",value:function getX(){return this.transform.loc.getX()}},{key:"setY",value:function setY(y){this.transform.loc.setY(y);return this}},{key:"getY",value:function getY(){return this.transform.loc.getY()}},{key:"setZ",value:function setZ(z){this.transform.loc.setZ(z);return this}},{key:"getZ",value:function getZ(){return this.transform.loc.getZ()}},{key:"setLoc",value:function setLoc(x,y,z){this.transform.loc.set(x,y,z);return this}},{key:"getLoc",value:function getLoc(){return this.transform.loc}//absolute position
},{key:"getAbsoluteX",value:function getAbsoluteX(){}},{key:"getAbsoluteY",value:function getAbsoluteY(){}//rotation
},{key:"setXRot",value:function setXRot(x){this.transform.rot.setX(x);return this}},{key:"getXRot",value:function getXRot(){return this.transform.rot.getX()}},{key:"setYRot",value:function setYRot(y){this.transform.rot.setY(y);return this}},{key:"getYRot",value:function getYRot(){return this.transform.rot.getY()}},{key:"setZRot",value:function setZRot(z){this.transform.rot.setZ(z);return this}},{key:"getZRot",value:function getZRot(){return this.transform.rot.getZ()}},{key:"setRot",value:function setRot(x,y,z){this.transform.rot.set(x,y,z);return this}},{key:"getRot",value:function getRot(){return this.transform.rot}//scale
},{key:"getScale",value:function getScale(){return this.transform.scale}},{key:"setScale",value:function setScale(scale){this.transform.scale=scale;this.__updateAABB();this.__triggerScaleChange();return this}},{key:"onScaleChange",value:function onScaleChange(func){var index=this.transform.scaleListeners.indexOf(func);if(index==-1)this.transform.scaleListeners.push(func);return this}},{key:"offScaleChange",value:function offScaleChange(func){var index=this.transform.scaleListeners.indexOf(func);if(index!=-1)this.transform.scaleListeners.splice(index,1);return this}},{key:"__triggerScaleChange",value:function __triggerScaleChange(){for(var i=0;i<this.transform.scaleListeners.length;i++){this.transform.scaleListeners[i].call(this,this.transform.scale)}}//velocity
},{key:"getVelo",value:function getVelo(){return this.velo.loc}},{key:"getRotVelo",value:function getRotVelo(){return this.velo.rot}},{key:"getScaleVelo",value:function getScaleVelo(){return this.velo.scale}},{key:"setScaleVelo",value:function setScaleVelo(scaleVelo){this.velo.scale=scaleVelo;return this}//targetting
},{key:"setTargetLoc",value:function setTargetLoc(loc,friction,speed,onReach){if(typeof friction=="function"){onReach=friction;friction=null}else if(typeof speed=="function"){onReach=speed;speed=null}this.getVelo().setLength(0);this.target.loc=loc;if(friction!=null)this.target.friction.loc=friction;if(speed)this.target.speed.loc=speed;if(onReach)this.target.callback.loc=onReach;return this}},{key:"setTargetRot",value:function setTargetRot(rot,friction,speed,onReach){if(typeof friction=="function"){onReach=friction;friction=null}else if(typeof speed=="function"){onReach=speed;speed=null}this.target.rot=rot;if(friction!=null)this.target.friction.rot=friction;if(speed)this.target.speed.rot=speed;if(onReach)this.target.callback.rot=onReach;return this}},{key:"setTargetScale",value:function setTargetScale(scale,friction,speed,onReach){if(typeof friction=="function"){onReach=friction;friction=null}else if(typeof speed=="function"){onReach=speed;speed=null}this.target.scale=scale;if(friction!=null)this.target.friction.scale=friction;if(speed)this.target.speed.scale=speed;if(onReach)this.target.callback.scale=onReach;return this}//color
},{key:"setColor",value:function setColor(color){this.color=color;this.setAlpha(1-Math.floor(color/16777215)/255);return this}},{key:"getColor",value:function getColor(){return this.color}},{key:"setAlpha",value:function setAlpha(alpha){this.alpha=alpha;return this}},{key:"getAlpha",value:function getAlpha(){return this.alpha}//event handlers
},{key:"__registerListener",value:function __registerListener(type,listener){if(this.listeners[type].indexOf(listener)==-1)this.listeners[type].push(listener);this.__updateInteraction();return this}},{key:"__deregisterListener",value:function __deregisterListener(type,listener){var index=this.listeners[type].indexOf(listener);if(index!=-1)this.listeners[type].splice(index,1);this.__updateInteraction();return this}},{key:"__triggerListener",value:function __triggerListener(type){var args=Array.from(arguments);args.shift();var ls=this.listeners[type];for(var i=0;i<ls.length;i++){if(ls[i].apply(this,args))return true}}},{key:"onClick",value:function onClick(func){return this.__registerListener("mouseClick",func)}},{key:"offClick",value:function offClick(func){return this.__deregisterListener("mouseClick",func)}},{key:"__triggerClick",value:function __triggerClick(event){return this.__triggerListener("mouseClick",event)}},{key:"onHover",value:function onHover(func){return this.__registerListener("mouseHover",func)}},{key:"offHover",value:function offHover(func){return this.__deregisterListener("mouseHover",func)}},{key:"__triggerHover",value:function __triggerHover(hover,event){return this.__triggerListener("mouseHover",hover,event)}},{key:"onMousePress",value:function onMousePress(func){return this.__registerListener("mousePress",func)}},{key:"offMousePress",value:function offMousePress(func){return this.__deregisterListener("mousePress",func)}},{key:"__triggerMousePress",value:function __triggerMousePress(down,event){return this.__triggerListener("mousePress",down,event)}},{key:"onMouseScroll",value:function onMouseScroll(func){return this.__registerListener("mouseScroll",func)}},{key:"offMouseScroll",value:function offMouseScroll(func){return this.__deregisterListener("mouseScroll",func)}},{key:"__triggerMouseScroll",value:function __triggerMouseScroll(amount,event){return this.__triggerListener("mouseScroll",amount,event)}},{key:"onMouseMove",value:function onMouseMove(func){return this.__registerListener("mouseMove",func)}},{key:"offMouseMove",value:function offMouseMove(func){return this.__deregisterListener("mouseMove",func)}},{key:"__triggerMouseMove",value:function __triggerMouseMove(pos,event){return this.__triggerListener("mouseMove",pos,event)}},{key:"onKeyPress",value:function onKeyPress(func){return this.__registerListener("keyPress",func)}},{key:"offKeyPress",value:function offKeyPress(func){return this.__deregisterListener("keyPress",func)}},{key:"__triggerKeyPress",value:function __triggerKeyPress(down,key,event){return this.__triggerListener("keyPress",down,key,event)}//enable/disable interaction
},{key:"__updateInteraction",value:function __updateInteraction(internally){if(!this.interactionDisabled)if(this.listeners.mouseClick.length==0&&this.listeners.mouseHover.length==0&&this.listeners.mousePress.length==0&&this.listeners.mouseScroll.length==0&&this.listeners.mouseMove.length==0&&this.listeners.keyPress.length==0)this.disableInteraction(true);else this.enableInteraction(true)}},{key:"enableInteraction",value:function enableInteraction(internally){if(!internally)this.interactionsDisabled=false}},{key:"disableInteraction",value:function disableInteraction(internally){if(!internally)this.interactionsDisabled=true}//update
},{key:"onUpdate",value:function onUpdate(listener){if(this.listeners.update.indexOf(listener)==-1)this.listeners.update.push(listener);this.__updateUpdates();return this}},{key:"offUpdate",value:function offUpdate(listener){var index=this.listeners.update.indexOf(listener);if(index!=-1)this.listeners.update.splice(index,1);this.__updateUpdates();return this}},{key:"__triggerUpdate",value:function __triggerUpdate(){for(var i=0;i<this.listeners.update.length;i++){this.listeners.update[i].apply(this,arguments)}return this}//enable/disable updates
},{key:"__updateUpdates",value:function __updateUpdates(){if(!this.updatesDisabled)if(this.listeners.update.length==0)this.disableUpdates(true);else this.enableUpdates(true)}},{key:"enableUpdates",value:function enableUpdates(internally){if(!internally)this.updatesDisabled=false;this.graphics.activateShape(this);return this}},{key:"disableUpdates",value:function disableUpdates(internally){if(!internally)this.updatesDisabled=true;this.graphics.deactivateShape(this);return this}//parent shape
},{key:"__setParentShape",value:function __setParentShape(parent){this.parentShape=parent;this.__triggerRenderChange();return this}},{key:"getParentShape",value:function getParentShape(){return this.parentShape}},{key:"getWorldLoc",value:function getWorldLoc(){return this.getLoc()}},{key:"getWorldScale",value:function getWorldScale(){return this.getScale()}},{key:"getWorldAngle",value:function getWorldAngle(){return this.getAngle()}//add or remove from graphics
},{key:"getGraphics",value:function getGraphics(){return this.graphics}},{key:"add",value:function add(){this.graphics.__registerShape(this);this.__updateUpdates();var tree=this.__getTree();if(tree&&this.storeInSpatialTree)tree.insert(this);this.isRendered=true;this.isAlive=true;this.__triggerRenderChange();return this}},{key:"remove",value:function remove(dontDelete){this.graphics.__deregisterShape(this);//indicate that the node is being removed
this.isAlive=false;if(dontDelete)return this;return this.__delete();//fully remove it without an animation
}},{key:"__delete",value:function __delete(){this.graphics.__deregisterShape(this,true);//remove the node entirely
this.disableUpdates(true);var tree=this.__getTree();if(tree&&this.storeInSpatialTree)tree.remove(this);this.isRendered=false;this.__triggerRenderChange();return this}},{key:"getIsRendered",value:function getIsRendered(){return this.isRendered}},{key:"getIsAlive",value:function getIsAlive(){return this.isAlive}//add render listener
},{key:"onRendererChange",value:function onRendererChange(func){var index=this.isRenderedListeners.indexOf(func);if(index==-1)this.isRenderedListeners.push(func);return this}},{key:"offRendererChange",value:function offRendererChange(func){var index=this.isRenderedListeners.indexOf(func);if(index!=-1)this.isRenderedListeners.splice(index,1);return this}},{key:"__triggerRenderChange",value:function __triggerRenderChange(){if(this.parentShape)this.isRendered=this.parentShape.isRendered;for(var i=0;i<this.isRenderedListeners.length;i++){this.isRenderedListeners[i].call(this,this.isRendered)}}//physics methods
},{key:"getVecTo",value:function getVecTo(x,y,z){if(x instanceof AbstractShape)x=x.getLoc();return new Vec(x,y,z).sub(this.getLoc())}//spatial tree methods
},{key:"__getRadius",value:function __getRadius(){return 0}},{key:"__getRadiusPadding",value:function __getRadiusPadding(){return this.__getRadius()*this.getWorldScale()/2}},{key:"__getTree",value:function __getTree(){return this.graphics.getSpatialTree()}},{key:"__updateAABB",value:function __updateAABB(){if(this.storeInSpatialTree){var minRad=this.__getRadius()*this.getWorldScale();var loc=this.getWorldLoc();//check whether the shape moved outside of the loose bounding box
if(this.aabb.minX>loc.getX()-minRad||this.aabb.minY>loc.getY()-minRad||this.aabb.minZ>loc.getZ()-minRad||this.aabb.maxX<loc.getX()+minRad||this.aabb.maxY<loc.getY()+minRad||this.aabb.maxZ<loc.getZ()+minRad){//remove data from the tree
var tree=this.__getTree();if(tree)tree.remove(this);//update the bounding box
var maxRad=minRad+this.__getRadiusPadding();this.aabb={minX:loc.getX()-maxRad,minY:loc.getY()-maxRad,minZ:loc.getZ()-maxRad,maxX:loc.getX()+maxRad,maxY:loc.getY()+maxRad,maxZ:loc.getZ()+maxRad};//reinsert the data into the tree
if(tree)tree.insert(this)}}return this}},{key:"search",value:function search(radius,filter){var tree=this.__getTree();if(tree){//search the tree
var loc=this.getWorldLoc();var results=tree.search({minX:loc.getX()-radius,minY:loc.getY()-radius,minZ:loc.getZ()-radius,maxX:loc.getX()+radius,maxY:loc.getY()+radius,maxZ:loc.getZ()+radius});var This=this;if(filter)//apply the filter and make sure to not include 'this'
return results.filter(function(val){return val!=This&&filter.call(val,val)});//only filter such that 'this' isn't returned
return results.filter(function(val){return val!=This})}return[]}}]);return AbstractShape}();/*
    Generalized NodeShape abstract class that manages sub shapes
    Author: Tar van Krieken
    Starting Date: 16/5/2018, but the content was initially part of 2d/Shapes/NodeShape.js
*/var AbstractNodeShape=function(_AbstractShape){_inherits(AbstractNodeShape,_AbstractShape);//will 'extend' a concrete shape
function AbstractNodeShape(){_classCallCheck(this,AbstractNodeShape);return _possibleConstructorReturn(this,(AbstractNodeShape.__proto__||Object.getPrototypeOf(AbstractNodeShape)).call(this))}//constructor will never be used
_createClass(AbstractNodeShape,[{key:"__setupNodeShape",value:function __setupNodeShape(node){//acts as the constructor
this.node=node;this.connectionHasBeenSetup=false;//track if an initial connection has ever been made
//keep track of some tree related properties to decide how to grow and shrink the visualisation
this.parent=null;this.children=[];this.__init();//seperate method in order to allow for it to be overwritten
//save state data
this.state={expanded:this.node.getChildren().length==0,selected:false,highlighted:false,focused:false,dragged:false};//setup connection
var parent=this.__getParentFromNode();this.__connectParent(parent)}},{key:"getNode",value:function getNode(){return this.node}},{key:"destroy",value:function destroy(callback){this.getNode().removeShape(this.graphics.getUID(),this);this.destroyCallback=callback;this.remove();this.graphics.__deregisterShapeNode(this);return this}},{key:"getVisualisation",value:function getVisualisation(){return this.getGraphics()}//rendering related methods
},{key:"__show",value:function __show(){}//method to be extended to animate the appearance of the node
},{key:"__hide",value:function __hide(){return true}//method to be extended to animate the dissapearance of the node
},{key:"__stateChanged",value:function __stateChanged(field,val,oldState){}//method to be extended to update the visuals to represent the state
},{key:"__connectParent",value:function __connectParent(parent){}//method to be extended to connect the parent shape
},{key:"__changeState",value:function __changeState(field,value){var oldState=Object.assign({},this.state);this.state[field]=value;var changed=oldState[field]!=this.state[field];this.__stateChanged(changed?field:null,changed?value:null,oldState);return this}//to be used when creating child or parent instances
},{key:"__getClass",value:function __getClass(node){//attempt to get from graphics
var getFromGFX=this.graphics.__getNodeShapeClass;if(getFromGFX)return getFromGFX.call(this.graphics,Visualisation2d.classes,node);//otherwise return this class
return this.__proto__.constructor}},{key:"__init",value:function __init(){//initialise node connection
var UID=this.graphics.getUID();var prevShape=this.node.getShape(UID);this.graphics.__registerShapeNode(this);if(prevShape==this)return;//this shape has already been set up
if(prevShape!=null){// it shouldn't occur that 1 node gets created twice
console.warn("A shape in the tree got overwritten",prevShape);prevShape.remove()}this.node.addShape(UID,this)}//adding/removing
},{key:"__addNode",value:function __addNode(){if(this.children.length==0){//otherwise it is already added
//register shape as root and leave, as no parent or children are set up yet
this.graphics.__registerShapeLeave(this);this.graphics.__registerShapeRoot(this);if(this.__getChildNodes().length!=this.children.length)this.graphics.__registerShapeCollapsed(this);//initially a node is never expanded upon creation
this.__changeState("expanded",false);//connect the parent and child nodes
var parent=this.__getParentFromNode(true);if(parent)this.__setParent(parent);var children=this.__getChildrenFromNode(true);for(var i=0;i<children.length;i++){this.__addChild(children[i])}//update visuals for the state
this.__stateChanged(null,null,this.state);this.__show()}return this}},{key:"__removeNode",value:function __removeNode(){return!this.__hide()}},{key:"__deleteNode",value:function __deleteNode(){//test: keep the node around, but don't render it
// //if the shape is deleted from the visualisation, disconnect it from the tree
// if(this.graphics && this.node)
//     this.node.removeShape(this.graphics.getUID());
//remove itself from parent
parent=this.getParent();if(parent)parent.__removeChild(this);//remove fron children
for(var i=0;i<this.children.length;i++){this.children[i].__setParent(null)}//clean up own relations
this.__setParent(null);this.children=[];//indicate that this shape is no longer anything in tree
this.graphics.__deregisterShapeRoot(this);this.graphics.__deregisterShapeCollapsed(this);this.graphics.__deregisterShapeLeave(this);if(this.destroyCallback){//a method that listens for the destroy method to finish
this.destroyCallback();delete this.destroyCallback}return this}//relation methods
},{key:"__setParent",value:function __setParent(parentShape){if(this.parent!=parentShape){this.parent=parentShape;if(parentShape){parentShape.__addChild(this);//will only be added if it wasn't already
this.graphics.__deregisterShapeRoot(this);//indicate that this shape is no longer a root
}else{this.graphics.__registerShapeRoot(this);//indicate that this shape is now a root
}}return this}},{key:"__addChild",value:function __addChild(childShape){var index=this.children.indexOf(childShape);if(index==-1){this.children.push(childShape);childShape.__setParent(this);//will only be set if it wasn't already
if(this.children.length==1)this.graphics.__deregisterShapeLeave(this);//indicate that this shape is no longer a leave
if(this.__getChildNodes().length==this.children.length){this.graphics.__deregisterShapeCollapsed(this);//indicate that there is nothing left to expand
this.__changeState("expanded",true)}}return this}},{key:"__removeChild",value:function __removeChild(childShape){var index=this.children.indexOf(childShape);if(index!=-1){if(this.__getChildNodes().length==this.children.length)this.graphics.__registerShapeCollapsed(this);//indicate that there is something left to expand
this.children.splice(index,1);if(this.getIsAlive()){//don't change to leave if it was only for the animating process
if(this.children.length==0)this.graphics.__registerShapeLeave(this);//indicate that this shape is now a leave
this.__changeState("expanded",false)}}return this}},{key:"getParent",value:function getParent(onlyAlive){if(!onlyAlive||this.parent&&this.parent.getIsAlive())return this.parent}},{key:"isParent",value:function isParent(shape){return this.parent==shape}},{key:"isRoot",value:function isRoot(){return!this.parent}},{key:"isLeave",value:function isLeave(){return this.children.length==0}},{key:"getChildren",value:function getChildren(onlyAlive){if(!onlyAlive)return this.children;var ret=[];for(var i=0;i<this.children.length;i++){var child=this.children[i];if(child.getIsAlive())ret.push(child)}return ret}},{key:"isChild",value:function isChild(shape){return this.children.indexOf(shape)!=-1}},{key:"getAncestors",value:function getAncestors(depth,onlyAlive){if(depth==null)depth=Infinity;if(depth<=0)return[];var ret=[];var p=this.getParent(onlyAlive);if(p){ret.push(p);ret.push.apply(p,p.getAncestors(depth-1))}return ret}},{key:"getAncestorsTo",value:function getAncestorsTo(shape){var ret=[];var p=this.getParent();if(p&&p!=shape){ret.push(p);ret.push.apply(p,p.getAncestors(depth-1))}return ret}},{key:"getDescendants",value:function getDescendants(depth,onlyAlive){if(depth==null)depth=Infinity;if(depth<=0)return[];var ret=[];var children=this.getChildren(onlyAlive);ret.push.apply(ret,children);for(var i=0;i<children.length;i++){var child=children[i];ret.push.apply(ret,child.getDescendants(depth-1))}return ret}},{key:"getConnectedNodeShape",value:function getConnectedNodeShape(onlyAlive){var parent=this.getParent(onlyAlive);if(parent)return parent;return this.getChildren(onlyAlive)[0]}},{key:"__getParentFromNode",value:function __getParentFromNode(requiresRendered){//get parent node through the tree, as it might not have been connected yet
var parentNode=this.__getParentNode();if(parentNode){var shape=parentNode.getShape(this.graphics.getUID());return shape.getIsRendered()||!requiresRendered?shape:undefined}}},{key:"__getChildrenFromNode",value:function __getChildrenFromNode(requiresRendered){//get child nodes through the tree, as they might not have been connected yet
var UID=this.graphics.getUID();var children=[];var nodeChildren=this.__getChildNodes();if(nodeChildren){for(var i=0;i<nodeChildren.length;i++){var shape=nodeChildren[i].getShape(UID);if(shape&&(shape.getIsRendered()||!requiresRendered))children.push(shape)}}return children}//tree node retrieval methods (instead of shapes)
},{key:"__getMissingChildNodes",value:function __getMissingChildNodes(){var UID=this.graphics.getUID();var children=[];var nodeChildren=this.__getChildNodes();if(nodeChildren){for(var i=0;i<nodeChildren.length;i++){var shape=nodeChildren[i].getShape(UID);if(!shape||!shape.getIsRendered())children.push(nodeChildren[i])}}return children}},{key:"__getChildNodes",value:function __getChildNodes(){return this.node.getChildren()}},{key:"__getParentNode",value:function __getParentNode(){return this.node.getParent()}//tree statistics methods
},{key:"getDepth",value:function getDepth(){return this.node.getDepth()}},{key:"getIndex",value:function getIndex(){return this.__getParentNode()?this.__getParentNode().getChildren().indexOf(this.node):0}//methods for creating parent/children nodes
},{key:"__createChildNodeShape",value:function __createChildNodeShape(node){return new(this.__getClass(node))(this.getGraphics(),node)}},{key:"createParent",value:function createParent(dontAdd){if(!this.getParent()){//make sure there isn't already a parent shape
var UID=this.graphics.getUID();var parentNode=this.__getParentNode();if(parentNode){var shape=parentNode.getShape(UID);// shape should always exist, can't create child without parent
// if(!shape)
//     shape = this.__createNodeShape(parentNode);
if(!dontAdd)shape.add();return shape}}}},{key:"createAncestors",value:function createAncestors(depth,dontAdd){//depth indicates how many layers to create
if(depth==null)depth=1;var ret=[];if(depth>=1){var p=this.createParent(dontAdd);if(p)ret.push(p);//only add p if it waas just created
var p=this.getParent();if(p)ret.push.apply(ret,p.createAncestors(depth-1));//recurse
}return ret}},{key:"destroyParent",value:function destroyParent(){var parent=this.getParent();if(parent){return parent.remove()}}},{key:"destroyAncestors",value:function destroyAncestors(depth,fully,keep){//depth indicates how many layers to keep
//fully indicates whether to also destroy descendants
if(depth==null)depth=0;var ret=[];var parent=this.getParent();if(parent&&parent!=keep){if(fully)ret.push.apply(ret,parent.destroyDescendants(0,[this]));//don't destroy this decendant
ret.push.apply(ret,parent.destroyAncestors(depth-1,fully));if(depth<=0)ret.push(parent.remove())}return ret}},{key:"createChild",value:function createChild(node,dontAdd){var UID=this.graphics.getUID();if(!node){var missingChildNodes=this.__getMissingChildNodes();node=missingChildNodes[0]}if(node){var shape=node.getShape(UID);if(!shape)shape=this.__createNodeShape(node);if(!dontAdd)shape.add();return shape}}},{key:"createChildren",value:function createChildren(dontAdd){var UID=this.graphics.getUID();var missingChildNodes=this.__getMissingChildNodes();var ret=[];for(var i=0;i<missingChildNodes.length;i++){var node=missingChildNodes[i];var shape=node.getShape(UID);if(!shape)shape=this.__createNodeShape(node);if(!dontAdd)shape.add();ret.push(shape)}return ret}},{key:"createDescendants",value:function createDescendants(depth,dontAdd){//depth indicates how many layers to create
if(depth==null)depth=1;var ret=[];if(depth>=1){ret.push.apply(ret,this.createChildren(dontAdd));var children=this.getChildren();for(var i=0;i<children.length;i++){var child=children[i];ret.push.apply(ret,child.createDescendants(depth-1))}}return ret}},{key:"destroyChildren",value:function destroyChildren(keep){//keep is a list of shapes you don't want to destroy
var children=this.getChildren();for(var i=children.length-1;i>=0;i--){var child=children[i];if(!keep||keep.indexOf(child)==-1)child.remove()}return children}},{key:"destroyDescendants",value:function destroyDescendants(depth,keep){//depth indicates how many layers to keep
//keep is a list of shapes you don't want to destroy
if(depth==null)depth=0;if(keep&&!(keep instanceof Array))keep=[keep];var ret=[];var children=this.getChildren();for(var i=0;i<children.length;i++){var child=children[i];if(!keep||keep.indexOf(child)==-1)ret.push.apply(ret,child.destroyDescendants(depth-1,keep))}if(depth<=0)ret.push.apply(ret,this.destroyChildren(keep));return ret}//methods for changing the state and synchronizing these changes
},{key:"highlight",value:function highlight(){if(!this.state.highlighted)this.graphics.setShapeState("highlighted",this)}},{key:"dehighlight",value:function dehighlight(forwarded){if(this.state.highlighted)this.graphics.setShapeState("highlighted",null)}},{key:"select",value:function select(forwarded){if(!this.state.selected)this.graphics.setShapeState("selected",this)}},{key:"deselect",value:function deselect(forwarded){if(this.state.selected)this.graphics.setShapeState("selected",null)}},{key:"focus",value:function focus(){if(!this.state.focused)this.graphics.setShapeState("focused",this)}},{key:"defocus",value:function defocus(){if(this.state.focused)this.graphics.setShapeState("focused",null)}}]);return AbstractNodeShape}(AbstractShape);/*
    Generalized Visualisation abstract class that manages visualisation aspects of the graphics
    Author: Tar van Krieken
    Starting Date: 16/5/2018, but the content was initially part of 2d/Visualisation.js
*/var AbstractVisualisation=function(_AbstractGraphics){_inherits(AbstractVisualisation,_AbstractGraphics);//will 'extend' concrete graphics
function AbstractVisualisation(){_classCallCheck(this,AbstractVisualisation);return _possibleConstructorReturn(this,(AbstractVisualisation.__proto__||Object.getPrototypeOf(AbstractVisualisation)).call(this))}//constructor will never be used
_createClass(AbstractVisualisation,[{key:"__setupVisualisation",value:function __setupVisualisation(tree,options){//acts as the constructor
this.tree=tree;this.options=options;this.shapes.root=[];//shapes that don't have visible parents
this.shapes.leave=[];//shapes that don't have any children
this.shapes.collapsed=[];//shapes that don't show all their children
this.shapes.node=[];//all nodes ever created (for disposal usage)
this.shapes.unique={focused:null,//the shape in the center
selected:null,//the highlighted shape by clicking
dragging:null,//the shape that is being dragged around
highlighted:null//the highlighted shape by hovering
};this.__setupRoot();this.__setupOptions(options);this.DOMEventListeners.mouseUp=function(){if(this.shapes.unique.dragging)this.shapes.unique.dragging.__changeState("dragged",false);this.shapes.unique.dragging=null}.bind(this);$(document).on("mouseup",this.DOMEventListeners.mouseUp)}//setup
},{key:"__setupOptions",value:function __setupOptions(options){}},{key:"synchronizeNode",value:function synchronizeNode(type,node,forwarded){var shape=node.getShape(this.getUID());if(this.shapes.unique[type])this.shapes.unique[type].__changeState(type,false);if(type=="focused"&&!shape){shape=this.createNodeShape(node).add();if(!shape.getConnectedNodeShape()){//shape is not connected with other existing shapes
//get rid of all existing shapes, except shape
for(var i=this.shapes.root.length-1;i>=0;i--){var root=this.shapes.root[i];if(root!=shape){root.destroyDescendants(0,shape);root.remove()}}}}this.shapes.unique[type]=shape;if(shape)shape.__changeState(type,true);//forward to other visualizations, if this wasn't a forward of itself
if(!forwarded)VisualisationHandler.synchronizeNode(type,node,this);return this}},{key:"setShapeState",value:function setShapeState(type,shape){//a method to synchonize nodes to be called from the nodeShape
var node=shape.getNode&&shape.getNode();this.synchronizeNode(type,node);return this}//dragging (not synchronized)
},{key:"dragShape",value:function dragShape(shape){if(this.shapes.unique.dragging)this.shapes.unique.dragging.__changeState("dragged",false);this.shapes.unique.dragging=shape;if(shape)shape.__changeState("dragged",true);return this}//shape dragging
},{key:"__onUpdate",value:function __onUpdate(deltaTime){if(this.shapes.unique.dragging)this.shapes.unique.dragging.__onDrag(this.getMouseLoc());_get(AbstractVisualisation.prototype.__proto__||Object.getPrototypeOf(AbstractVisualisation.prototype),"__onUpdate",this).call(this,deltaTime)}//classes
},{key:"__getNodeShapeClass",value:function __getNodeShapeClass(VIZ,node){}//create node shape
},{key:"createNodeShape",value:function createNodeShape(node){var UID=this.getUID();var shape=node.getShape(UID);if(shape){//a node shape already exists, simply return that one
return shape}else{//find closest ancestor for which a shape does exists:
var path=[node];var p=node.getParent();while(!p.getShape(UID)){path.unshift(p);p=p.getParent()}//create entire path from parent to node
for(var i=0;i<path.length;i++){var node=path[i];var parentShape=node.getParent().getShape(UID);var nodeShape=parentShape.createChild(node,true);// nodeShape.add().remove();   //connect the shape, but stop rendering immediately after
path.splice(i,1,nodeShape);//replace node with nodeShape in path
}return path[path.length-1]}}//destroy
},{key:"__destroy",value:function __destroy(callback){var This=this;var finish=function finish(){This.getCanvas().remove();if(callback)callback.call(This)};var nodes=this.getShapesNode();var destroyLeft=nodes.length;var countFunc=function countFunc(){if(--destroyLeft==0)finish()};for(var i=nodes.length-1;i>=0;i--){nodes[i].destroy(countFunc)}}//dynamic tree growing/shrinking methods
},{key:"__registerShapeType",value:function __registerShapeType(type,shape){var shapes=this.__getShapesType(type);var index=shapes.indexOf(shape);if(index==-1)shapes.push(shape);return this}},{key:"__deregisterShapeType",value:function __deregisterShapeType(type,shape){var shapes=this.__getShapesType(type);var index=shapes.indexOf(shape);if(index!=-1)shapes.splice(index,1);return this}},{key:"__getShapesType",value:function __getShapesType(type){return this.shapes[type]}},{key:"__registerShapeRoot",value:function __registerShapeRoot(shape){return this.__registerShapeType("root",shape)}},{key:"__deregisterShapeRoot",value:function __deregisterShapeRoot(shape){return this.__deregisterShapeType("root",shape)}},{key:"getShapesRoot",value:function getShapesRoot(){return this.__getShapesType("root")}},{key:"__registerShapeLeave",value:function __registerShapeLeave(shape){return this.__registerShapeType("leave",shape)}},{key:"__deregisterShapeLeave",value:function __deregisterShapeLeave(shape){return this.__deregisterShapeType("leave",shape)}},{key:"getShapesLeave",value:function getShapesLeave(){return this.__getShapesType("leave")}},{key:"__registerShapeCollapsed",value:function __registerShapeCollapsed(shape){return this.__registerShapeType("collapsed",shape)}},{key:"__deregisterShapeCollapsed",value:function __deregisterShapeCollapsed(shape){return this.__deregisterShapeType("collapsed",shape)}},{key:"getShapesCollapsed",value:function getShapesCollapsed(){return this.__getShapesType("collapsed")}},{key:"__registerShapeNode",value:function __registerShapeNode(shape){return this.__registerShapeType("node",shape)}},{key:"__deregisterShapeNode",value:function __deregisterShapeNode(shape){return this.__deregisterShapeType("node",shape)}},{key:"getShapesNode",value:function getShapesNode(){return this.__getShapesType("node")}},{key:"growTree",value:function growTree(growNodes,shrinkNodes){//grows towards the leaves
//clean up input data, making sure it is an array of nodes
if(!(growNodes instanceof Array))if(!growNodes)growNodes=this.getShapesCollapsed();else growNodes=[growNodes];if(!(shrinkNodes instanceof Array))if(!shrinkNodes)shrinkNodes=this.getShapesRoot();else shrinkNodes=[shrinkNodes];var ret;//find min depth node to grow
var growNode=growNodes[0];for(var j=1;j<growNodes.length;j++){var gn=growNodes[j];if(gn.getDepth()<growNode.getDepth())growNode=gn}if(growNode)ret=growNode.createChild();//remove some node if there are too many
if(this.getShapes().length>this.maxNodeCount){//find min depth node to remove
var shrinkNode=shrinkNodes[0];for(var j=1;j<shrinkNodes.length;j++){var sn=shrinkNodes[j];if(sn.getDepth()<shrinkNode.getDepth())shrinkNode=sn}if(shrinkNode)shrinkNode.remove()}return ret}},{key:"shrinkTree",value:function shrinkTree(growNodes,shrinkNodes){//grows towards the root
//clean up input data, making sure it is an array of nodes
if(!(growNodes instanceof Array))if(!growNodes)growNodes=this.getShapesRoot();else growNodes=[growNodes];if(!(shrinkNodes instanceof Array))if(!shrinkNodes)shrinkNodes=this.getShapesLeave();else shrinkNodes=[shrinkNodes];var ret;//find max depth node to grow
var growNode=growNodes[0];for(var j=1;j<growNodes.length;j++){var gn=growNodes[j];if(gn.getDepth()>growNode.getDepth())growNode=gn}if(growNode)ret=growNode.createParent();//remove some node if there are too many
if(this.getShapes().length>this.maxNodeCount){//find max depth node to remove
var shrinkNode=shrinkNodes[0];for(var j=1;j<shrinkNodes.length;j++){var sn=shrinkNodes[j];if(sn.getDepth()>shrinkNode.getDepth())shrinkNode=sn}if(shrinkNode)shrinkNode.remove()}return ret}}]);return AbstractVisualisation}(AbstractGraphics);/*
    2d camera class
    Author: Tar van Krieken
    Starting Date: 28/04/2018
*/var Camera2d=function(_AbstractCamera){_inherits(Camera2d,_AbstractCamera);function Camera2d(graphics){_classCallCheck(this,Camera2d);var _this4=_possibleConstructorReturn(this,(Camera2d.__proto__||Object.getPrototypeOf(Camera2d)).call(this,graphics));_this4.stage=graphics.__getStage();//update camera on pos/rot change
var This=_this4;_this4.loc.onChange(_this4.__updateLoc.bind(_this4));_this4.rot.onChange(_this4.__updateLoc.bind(_this4));//update camera pos
_this4.loc.set(0,0,0);return _this4}_createClass(Camera2d,[{key:"__updateLoc",value:function __updateLoc(){var angle=-this.getZRot();var vec=new Vec(this.loc).mul(-this.getScale()).addAngle(angle).add(this.graphics.getWidth()/2,this.graphics.getHeight()/2);this.stage.rotation=angle;this.stage.x=vec.getX();this.stage.y=vec.getY();// this.stage.x = -this.loc.getX()*this.scale;
// this.stage.y = this.graphics.getHeight()/2-this.loc.getY()*this.scale;
}},{key:"setScale",value:function setScale(scale){this.stage.scale.set(scale);_get(Camera2d.prototype.__proto__||Object.getPrototypeOf(Camera2d.prototype),"setScale",this).call(this,scale);this.__updateLoc();return this}},{key:"translateScreenToWorldLoc",value:function translateScreenToWorldLoc(x,y,z){var vec=new Vec(x,y,z);var size=new XYZ(this.graphics.getWidth(),this.graphics.getHeight());return vec.sub(size.mul(0.5)).div(this.getScale()).addAngle(this.getZRot()).add(this.getLoc())}},{key:"translateWorldToScreenLoc",value:function translateWorldToScreenLoc(x,y,z){var vec=new Vec(x,y,z);var size=new XYZ(this.graphics.getWidth(),this.graphics.getHeight());return vec.sub(this.getLoc()).addAngle(-this.getZRot()).mul(this.getScale()).add(size.mul(0.5))}}]);return Camera2d}(AbstractCamera);/*
    2d graphics class
    Author: Tar van Krieken
    Starting Date: 28/04/2018
*/var Graphics2d=function(_AbstractGraphics2){_inherits(Graphics2d,_AbstractGraphics2);function Graphics2d(width,height,container,preInit){_classCallCheck(this,Graphics2d);//create the graphics environment
var _this5=_possibleConstructorReturn(this,(Graphics2d.__proto__||Object.getPrototypeOf(Graphics2d)).call(this,width,height,container,preInit));_this5.app=new PIXI.Application(_this5.getWidth(),_this5.getHeight(),{transparent:true,antialias:true});//add graphics to the screen
var This=_this5;$(_this5.app.view).addClass("pixi");_this5.container.append(_this5.app.view);_this5.container.on("finishResize",function(event,size){var newSize={width:This.container.width(),height:This.container.height()};This.app.renderer.resize(newSize.width,newSize.height);This.size=newSize;This.stage.hitArea=new PIXI.Rectangle(-This.getWidth()/2,-This.getHeight()/2,This.getWidth(),This.getHeight());//update hitbox for mouse interaction
This.camera.__updateLoc()});//fix interaction bugs when hovering over an html shape
var m=_this5.app.renderer.plugins.interaction;m.interactionDOMElement.removeEventListener("pointerleave",m.onPointerOut,true);//register update listener, set to 30fps
_this5.updating=true;var last=Date.now();var delta=1/30;_this5.app.ticker.add(function(){var now=Date.now();if((now-last)/1000>delta){if(This.updating)This.__onUpdate(delta);last+=delta*1000;if(now-last>2000)last=now}});// PIXI.settings.TARGET_FPMS = 30/1000;    //set target fps to 30
//setup layered container
_this5.app.stage=new PIXI.display.Stage;_this5.app.stage.group.enableSort=true;_this5.group=new PIXI.display.Group(1,true);_this5.stage=new PIXI.display.Layer(_this5.group);_this5.stage.hitArea=new PIXI.Rectangle(-_this5.getWidth()/2,-_this5.getHeight()/2,_this5.getWidth(),_this5.getHeight());//setup hitbox for mouse interaction
_this5.app.stage.addChild(_this5.stage);//add event handlers
{_this5.mouse={x:0,y:0,pressed:false};var mouseMove=function mouseMove(data){This.mouse.x=data.data.global.x;This.mouse.y=data.data.global.y;This.mouse.clientX=data.data.originalEvent.clientX;This.mouse.clientY=data.data.originalEvent.clientY;This.__triggerMouseMove(new XYZ(data.data.global.x,data.data.global.y),data)};var mouseDown=function mouseDown(data){This.mouse.pressed=true;This.__triggerMousePress(true,data)};var mouseUp=function mouseUp(data){This.mouse.pressed=false;This.__triggerMousePress(false,data);This.__triggerClick(data)};var mouseScroll=function mouseScroll(data){This.__triggerMouseScroll(data.data.originalEvent.originalEvent.wheelDeltaY,data)};var keyPress=function keyPress(data){var key=data.data.originalEvent.key;This.__triggerKeyPress(data.data.originalEvent.type=="keydown",key?key.toLowerCase():key,data)};_this5.app.stage.interactive=true;_this5.app.stage.on("mousedown",mouseDown).on("touchstart",mouseDown).on("mouseup",mouseUp).on("mouseupoutside",mouseUp).on("touchend",mouseUp).on("touchendoutside",mouseUp).on("mousemove",mouseMove).on("touchmove",mouseMove).on("scroll",mouseScroll).on("keypress",keyPress)}//create scroll event and key events
{_this5.DOMEventListeners.scroll=function(event){var interactionData=m.getInteractionDataForPointerId(event);var interactionEvent=m.configureInteractionEventForDOMEvent(m.eventData,event,interactionData);m.processInteractive(interactionEvent,m.renderer._lastObjectRendered,function(interactionEvent,displayObject,hit){if(hit){m.dispatchEvent(displayObject,"scroll",interactionEvent)}},true)};_this5.DOMEventListeners.keypress=function(event){var interactionData=m.getInteractionDataForPointerId(event);if(event.type=="keyup")//remove keys even if released outside of visualisation
delete This.pressedKeys[event.key.toLowerCase()];//set target location
event.clientX=This.mouse.clientX;event.clientY=This.mouse.clientY;var interactionEvent=m.configureInteractionEventForDOMEvent(m.eventData,event,interactionData);m.processInteractive(interactionEvent,m.renderer._lastObjectRendered,function(interactionEvent,displayObject,hit){if(hit){m.dispatchEvent(displayObject,"keypress",interactionEvent)}},true)};$(window).on("mousewheel",_this5.DOMEventListeners.scroll);$(window).on("keydown",_this5.DOMEventListeners.keypress);$(window).on("keyup",_this5.DOMEventListeners.keypress)}//connect a camera
_this5.camera=new Camera2d(_this5);return _this5}_createClass(Graphics2d,[{key:"getCanvas",value:function getCanvas(){return this.getContainer().find("canvas.pixi")}//disposal
},{key:"destroy",value:function destroy(){$(window).off("mousewheel",this.DOMEventListeners.scroll);$(window).off("keydown",this.DOMEventListeners.keypress);$(window).off("keyup",this.DOMEventListeners.keypress);_get(Graphics2d.prototype.__proto__||Object.getPrototypeOf(Graphics2d.prototype),"destroy",this).call(this)}//start/stop rendering
},{key:"pause",value:function pause(fully){if(!fully){this.updating=false}else{this.app.stop()}}},{key:"start",value:function start(){this.updating=true;this.app.start()}//pixi specific methods
},{key:"__getStage",value:function __getStage(){return this.app.stage}},{key:"__getGroup",value:function __getGroup(){return this.group}},{key:"__getRenderer",value:function __getRenderer(){return this.app.renderer}//mouse  methods
},{key:"getMouseScreenLoc",value:function getMouseScreenLoc(){return this.mouse}},{key:"getMouseLoc",value:function getMouseLoc(){return this.camera.translateScreenToWorldLoc(this.getMouseScreenLoc())}},{key:"getMouseVec",value:function getMouseVec(x,y){var xyz;if(x instanceof AbstractShape)xyz=new Vec(x.getWorldLoc());else xyz=new Vec(x,y);var pos=this.getMouseLoc();return xyz.sub(pos)}},{key:"getMousePressed",value:function getMousePressed(){return this.mouse.pressed}}]);return Graphics2d}(AbstractGraphics);/*
    2d shape class
    Author: Tar van Krieken
    Starting Date: 28/04/2018
*/var Shape2d=function(_AbstractShape2){_inherits(Shape2d,_AbstractShape2);function Shape2d(graphics,color,preInit){_classCallCheck(this,Shape2d);var _this6=_possibleConstructorReturn(this,(Shape2d.__proto__||Object.getPrototypeOf(Shape2d)).call(this,graphics,preInit));_this6.gfx=_this6.__createGfx();_this6.setColor(color);_this6.gfx.zIndex=0;//orders the rendering of th shapes
//add listeners to change pos/rot
var This=_this6;var oldZ=0;_this6.getLoc().onChange(function(){This.gfx.x=this.getX();This.gfx.y=this.getY();var newZ=this.getZ();if(oldZ!=newZ){This.__updateZOrder();oldZ=newZ}});_this6.getRot().onChange(function(){This.gfx.rotation=this.getZ()});//add interaction events
{//add hover handlers
_this6.gfx.on("mouseover",function(data){if(This.__triggerHover(true,data))data.stopPropagation()});_this6.gfx.on("mouseout",function(data){if(This.__triggerHover(false,data))data.stopPropagation()});//add click handler
_this6.gfx.on("click",function(data){if(This.__triggerClick(data))data.stopPropagation()});//add mouse events
var mouseDown=function mouseDown(data){if(This.__triggerMousePress(true,data))data.stopPropagation()};var mouseUp=function mouseUp(data){if(This.__triggerMousePress(false,data))data.stopPropagation()};var mouseMove=function mouseMove(data){if(This.__triggerMouseMove(new XYZ(data.data.global.x,data.data.global.y),data))data.stopPropagation()};var mouseScroll=function mouseScroll(data){if(This.__triggerMouseScroll(data.data.originalEvent.originalEvent.wheelDeltaY,data))data.stopPropagation()};var keyPress=function keyPress(data){var key=data.data.originalEvent.key;if(This.__triggerKeyPress(data.data.originalEvent.type=="keydown",key?key.toLowerCase():key,data))data.stopPropagation()};_this6.gfx.on("mousedown",mouseDown).on("touchstart",mouseDown).on("mouseup",mouseUp).on("mouseupoutside",mouseUp).on("touchend",mouseUp).on("touchendoutside",mouseUp).on("mousemove",mouseMove).on("touchmove",mouseMove).on("scroll",mouseScroll).on("keypress",keyPress)}return _this6}_createClass(Shape2d,[{key:"__redraw",value:function __redraw(){}},{key:"__getGfx",value:function __getGfx(){return this.gfx}},{key:"__createGfx",value:function __createGfx(){return new PIXI.Graphics}},{key:"__updateZOrder",value:function __updateZOrder(){var zOrder=-this.getZ();this.gfx.zOrder=zOrder;if(this.parentShape)this.gfx.parentGroup=this.parentShape.__getGroup();else this.gfx.parentGroup=this.graphics.__getGroup()}//change scale
},{key:"setScale",value:function setScale(scale){this.gfx.scale.set(scale);return _get(Shape2d.prototype.__proto__||Object.getPrototypeOf(Shape2d.prototype),"setScale",this).call(this,scale)}//absolute coordinates, relative to the screen
},{key:"getAbsoluteX",value:function getAbsoluteX(){return this.gfx.worldTransform.tx}},{key:"getAbsoluteY",value:function getAbsoluteY(){return this.gfx.worldTransform.ty}//world location (when in other shape)
},{key:"getWorldLoc",value:function getWorldLoc(){if(this.parentShape){var p=this.parentShape;var vec=new Vec(this.getLoc());vec.mul(p.getScale()).addAngle(p.getAngle());vec.add(p.getWorldLoc());return vec}return this.getLoc()}},{key:"getWorldScale",value:function getWorldScale(){if(this.parentShape)return this.getScale()*this.getWorldScale();return _get(Shape2d.prototype.__proto__||Object.getPrototypeOf(Shape2d.prototype),"getWorldScale",this).call(this)}},{key:"getWorldAngle",value:function getWorldAngle(){if(this.parentShape)return this.getAngle()+this.getWorldAngle();return _get(Shape2d.prototype.__proto__||Object.getPrototypeOf(Shape2d.prototype),"getWorldAngle",this).call(this)}},{key:"isVisible",value:function isVisible(){var loc=this.getWorldLoc();var graphics=this.getGraphics();var camera=graphics.getCamera();var camLoc=camera.getLoc();var x=loc.getX()-camLoc.getX();var y=loc.getY()-camLoc.getY();var w=graphics.getWidth()/2/camera.getScale();var h=graphics.getHeight()/2/camera.getScale();var r=this.__getRadius()*this.getWorldScale();return x+r>-w&&x-r<w&&y+r>-h&&y-r<h}//method alias
},{key:"setAngle",value:function setAngle(angle){return this.setZRot(angle)}},{key:"getAngle",value:function getAngle(){return this.getZRot()}//update color
},{key:"setColor",value:function setColor(color){_get(Shape2d.prototype.__proto__||Object.getPrototypeOf(Shape2d.prototype),"setColor",this).call(this,color);this.__redraw();return this}},{key:"setAlpha",value:function setAlpha(alpha){this.gfx.alpha=alpha;return _get(Shape2d.prototype.__proto__||Object.getPrototypeOf(Shape2d.prototype),"setAlpha",this).call(this,alpha)}//enable/disabling interactions
},{key:"enableInteraction",value:function enableInteraction(internally){this.gfx.interactive=true;_get(Shape2d.prototype.__proto__||Object.getPrototypeOf(Shape2d.prototype),"enableInteraction",this).call(this,internally)}},{key:"disableInteraction",value:function disableInteraction(internally){this.gfx.interactive=false;_get(Shape2d.prototype.__proto__||Object.getPrototypeOf(Shape2d.prototype),"disableInteraction",this).call(this,internally)}//add to/remove from graphics
},{key:"add",value:function add(){_get(Shape2d.prototype.__proto__||Object.getPrototypeOf(Shape2d.prototype),"add",this).call(this);this.graphics.__getStage().addChild(this.gfx);this.__updateZOrder();return this}},{key:"__delete",value:function __delete(){this.graphics.__getStage().removeChild(this.gfx);_get(Shape2d.prototype.__proto__||Object.getPrototypeOf(Shape2d.prototype),"__delete",this).call(this)}//update zindex on parent changes
},{key:"__setParentShape",value:function __setParentShape(parent){_get(Shape2d.prototype.__proto__||Object.getPrototypeOf(Shape2d.prototype),"__setParentShape",this).call(this,parent);this.__updateZOrder();return this}//targetting ignore z
},{key:"__onUpdate",value:function __onUpdate(deltaTime){this.getVelo().setZ(0);if(this.target.loc){var delta=this.getVecTo(this.target.loc instanceof Function?this.target.loc.call(this):this.target.loc).setZ(0);var velo=this.getVelo();if(delta.getLength()<1*this.getScale()&&velo.getLength()<150*this.getScale()&&this.target.callback.loc){this.target.callback.loc.call(this);this.target.callback.loc=null}}return _get(Shape2d.prototype.__proto__||Object.getPrototypeOf(Shape2d.prototype),"__onUpdate",this).call(this,deltaTime)}}]);return Shape2d}(AbstractShape);/*
    A simple 2d rectangle shape
    Author: Tar van Krieken
    Starting Date: 28/04/2018
*/var CompoundShape2d=function(_Shape2d){_inherits(CompoundShape2d,_Shape2d);function CompoundShape2d(graphics,preInit){_classCallCheck(this,CompoundShape2d);var _this7=_possibleConstructorReturn(this,(CompoundShape2d.__proto__||Object.getPrototypeOf(CompoundShape2d)).call(this,graphics,null,preInit));_this7.shapes=[];//forward location change to children (world location)
var This=_this7;_this7.getLoc().onChange(function(){for(var i=0;i<This.shapes.length;i++){This.shapes[i].getLoc().__fireEvent()}});_this7.getRot().onChange(function(){for(var i=0;i<This.shapes.length;i++){This.shapes[i].getLoc().__fireEvent()}});return _this7}_createClass(CompoundShape2d,[{key:"__createGfx",value:function __createGfx(){return new PIXI.Sprite}//updating shapes
},{key:"addShape",value:function addShape(shape){for(var i=0;i<arguments.length;i++){var shape=arguments[i];if(this.shapes.indexOf(shape)==-1){this.shapes.push(shape);shape.__setParentShape(this)}}this.__redraw();return this}},{key:"removeShape",value:function removeShape(shape){for(var i=0;i<arguments.length;i++){var shape=arguments[i];var index=this.shapes.indexOf(shape);if(index!=-1){this.shapes.splice(index,1);shape.__setParentShape(null)}}this.__redraw();return this}//redraw shapes
},{key:"__redraw",value:function __redraw(){var aabb={minX:Infinity,maxX:-Infinity,minY:Infinity,maxY:-Infinity};var ix,ax,iy,ay;for(var i=0;i<this.shapes.length;i++){var shape=this.shapes[i];var r=shape.__getRadius()*shape.getScale();var l=shape.getLoc();if((ax=l.getX()+r)>aabb.maxX)aabb.maxX=ax;if((ix=l.getX()-r)<aabb.minX)aabb.minX=ix;if((ay=l.getY()+r)>aabb.maxY)aabb.maxY=ay;if((iy=l.getY()-r)<aabb.minY)aabb.minY=iy}var rt=PIXI.RenderTexture.create(aabb.maxX-aabb.minX,aabb.maxY-aabb.minY);for(var i=0;i<this.shapes.length;i++){var shape=this.shapes[i];shape.gfx.x-=aabb.minX;shape.gfx.y-=aabb.minY;this.graphics.__getRenderer().render(shape.gfx,rt,false);shape.gfx.x+=aabb.minX;shape.gfx.y+=aabb.minY}this.gfx.setTexture(rt);//update width and height
this.size={width:Math.max(-aabb.minX,aabb.maxX)*2,height:Math.max(-aabb.minY,aabb.maxY)*2};this.gfx.pivot.x=-aabb.minX;this.gfx.pivot.y=-aabb.minY}},{key:"__getRadius",value:function __getRadius(){var x=this.size.width/2;var y=this.size.height/2;return Math.sqrt(x*x+y*y)}//forward scale event
},{key:"__triggerScaleChange",value:function __triggerScaleChange(){_get(CompoundShape2d.prototype.__proto__||Object.getPrototypeOf(CompoundShape2d.prototype),"__triggerScaleChange",this).call(this);for(var i=0;i<this.shapes.length;i++){this.shapes[i].__triggerScaleChange()}}},{key:"__triggerRenderChange",value:function __triggerRenderChange(){_get(CompoundShape2d.prototype.__proto__||Object.getPrototypeOf(CompoundShape2d.prototype),"__triggerRenderChange",this).call(this);for(var i=0;i<this.shapes.length;i++){this.shapes[i].__triggerRenderChange()}}}]);return CompoundShape2d}(Shape2d);/*
    A shape that manages sub shapes
    Author: Tar van Krieken
    Starting Date: 30/04/2018
*/var ShapeGroup2d=function(_Shape2d2){_inherits(ShapeGroup2d,_Shape2d2);function ShapeGroup2d(graphics,preInit){_classCallCheck(this,ShapeGroup2d);var _this8=_possibleConstructorReturn(this,(ShapeGroup2d.__proto__||Object.getPrototypeOf(ShapeGroup2d)).call(this,graphics,null,preInit));_this8.shapes=[];_this8.radius=0;//forward location change to children (world location)
var This=_this8;_this8.getLoc().onChange(function(){for(var i=0;i<This.shapes.length;i++){This.shapes[i].getLoc().__fireEvent()}});_this8.getRot().onChange(function(){for(var i=0;i<This.shapes.length;i++){This.shapes[i].getLoc().__fireEvent()}});//create group
_this8.group=new PIXI.display.Group(1,true);return _this8}_createClass(ShapeGroup2d,[{key:"__createGfx",value:function __createGfx(){var layer=new PIXI.display.Layer(this.group);layer.group.enableSort=true;return layer}},{key:"__getGroup",value:function __getGroup(){return this.group}//shape interaction
},{key:"getShapes",value:function getShapes(){return this.shapes}},{key:"addShape",value:function addShape(shape){for(var i=0;i<arguments.length;i++){var shape=arguments[i];if(this.shapes.indexOf(shape)==-1){this.gfx.addChild(shape.gfx);this.shapes.push(shape);shape.__setParentShape(this)}}this.__updateRadius();return this}},{key:"removeShape",value:function removeShape(shape){for(var i=0;i<arguments.length;i++){var shape=arguments[i];this.gfx.removeChild(shape.gfx);var index=this.shapes.indexOf(shape);if(index!=-1){this.shapes.splice(index,1);shape.__setParentShape(null)}}this.__updateRadius();return this}//manage the radius
},{key:"__updateRadius",value:function __updateRadius(){this.radius=0;for(var i=0;i<this.shapes.length;i++){var shape=this.shapes[i];this.radius=Math.max(this.radius,new Vec(shape.getLoc()).getLength()+shape.__getRadius()*shape.getScale())}}},{key:"__getRadius",value:function __getRadius(){return this.radius}//forward scale event
},{key:"__triggerScaleChange",value:function __triggerScaleChange(){_get(ShapeGroup2d.prototype.__proto__||Object.getPrototypeOf(ShapeGroup2d.prototype),"__triggerScaleChange",this).call(this);for(var i=0;i<this.shapes.length;i++){this.shapes[i].__triggerScaleChange()}}},{key:"__triggerRenderChange",value:function __triggerRenderChange(){_get(ShapeGroup2d.prototype.__proto__||Object.getPrototypeOf(ShapeGroup2d.prototype),"__triggerRenderChange",this).call(this);for(var i=0;i<this.shapes.length;i++){this.shapes[i].__triggerRenderChange()}}}]);return ShapeGroup2d}(Shape2d);/*
    A node shape that manages sub shapes
    Author: Tar van Krieken
    Starting Date: 30/04/2018
*/var NodeShape2d=function(_ShapeGroup2d){_inherits(NodeShape2d,_ShapeGroup2d);function NodeShape2d(graphics,node,preInit){_classCallCheck(this,NodeShape2d);var _this9=_possibleConstructorReturn(this,(NodeShape2d.__proto__||Object.getPrototypeOf(NodeShape2d)).call(this,graphics,preInit));//attributes will just be stored in the object
_this9.__setupNodeShape(node);return _this9}//relation maintenance (needs super)
_createClass(NodeShape2d,[{key:"add",value:function add(){var ret=_get(NodeShape2d.prototype.__proto__||Object.getPrototypeOf(NodeShape2d.prototype),"add",this).call(this);this.__addNode();return ret}},{key:"remove",value:function remove(){return _get(NodeShape2d.prototype.__proto__||Object.getPrototypeOf(NodeShape2d.prototype),"remove",this).call(this,this.__removeNode())}},{key:"__delete",value:function __delete(){this.__deleteNode();return _get(NodeShape2d.prototype.__proto__||Object.getPrototypeOf(NodeShape2d.prototype),"__delete",this).call(this)}}]);return NodeShape2d}(ShapeGroup2d);//copy methods of abstractNodeShape
var keys=Object.getOwnPropertyNames(AbstractNodeShape.prototype);for(var i=0;i<keys.length;i++){NodeShape2d.prototype[keys[i]]=AbstractNodeShape.prototype[keys[i]]}/*
    A simple 2d rectangle shape
    Author: Tar van Krieken
    Starting Date: 12/05/2018
*/var HtmlShape2d=function(_Shape2d3){_inherits(HtmlShape2d,_Shape2d3);function HtmlShape2d(graphics,html,preInit){_classCallCheck(this,HtmlShape2d);var _this10=_possibleConstructorReturn(this,(HtmlShape2d.__proto__||Object.getPrototypeOf(HtmlShape2d)).call(this,graphics,null,preInit));_this10.element=$("<div class=HTMLshape style=display:inline-block;position:absolute;color:white;z-index:1000>"+"</div>");_this10.setHtml(html);_this10.setContainer(graphics.getContainer());_this10.setInteractive(false);_this10.visCont=graphics.getCanvas();var This=_this10;_this10.getLoc().onChange(function(){This.__updateLoc()});return _this10}//interactive means that it catches mouse events
_createClass(HtmlShape2d,[{key:"setInteractive",value:function setInteractive(interactive){this.interactive=interactive;if(interactive)this.element.addClass("interactive").css("pointer-events","all");else this.element.removeClass("interactive").css("pointer-events","none");return this}},{key:"getInteractive",value:function getInteractive(){return this.interactive}//container methods
},{key:"setContainer",value:function setContainer(container){this.container=$(container);return this}},{key:"getContainer",value:function getContainer(){return this.container}//html methods
},{key:"setHtml",value:function setHtml(html){this.element.html(html);return this}},{key:"getHtml",value:function getHtml(){return this.element.contents()}},{key:"getElement",value:function getElement(){return this.element}//add/remove element from page
},{key:"__addToPage",value:function __addToPage(){this.getContainer().append(this.element);var shapes=this.graphics.getShapesHtml();if(shapes.indexOf(this)==-1)shapes.push(this);this.__updateLoc();return this}},{key:"__removeFromPage",value:function __removeFromPage(){this.element.remove();var shapes=this.graphics.getShapesHtml();var index=shapes.indexOf(this);if(index!=-1)shapes.splice(index,1);return this}},{key:"add",value:function add(){_get(HtmlShape2d.prototype.__proto__||Object.getPrototypeOf(HtmlShape2d.prototype),"add",this).call(this);this.__addToPage();return this}},{key:"remove",value:function remove(){this.__removeFromPage();return _get(HtmlShape2d.prototype.__proto__||Object.getPrototypeOf(HtmlShape2d.prototype),"remove",this).call(this)}},{key:"__setParentShape",value:function __setParentShape(shape){var ret=_get(HtmlShape2d.prototype.__proto__||Object.getPrototypeOf(HtmlShape2d.prototype),"__setParentShape",this).call(this,shape);if(shape)this.__addToPage();else this.__removeFromPage();return ret}//scale handeling
},{key:"setScale",value:function setScale(scale){_get(HtmlShape2d.prototype.__proto__||Object.getPrototypeOf(HtmlShape2d.prototype),"setScale",this).call(this,scale);this.element.css("transform","scale("+Math.floor(scale*100)/100+")");return this}//method to keep the html element in the correct location
},{key:"__updateLoc",value:function __updateLoc(){var loc=this.getGraphics().getCamera().translateWorldToScreenLoc(this.getWorldLoc());var o=this.visCont.offset();// var c = this.getContainer().offset();
o.left+=loc.getX()-this.element.width()*this.transform.scale/2;//-c.left;
o.top+=loc.getY()-this.element.height()*this.transform.scale/2;//-c.top;
this.element.offset(o);return this}//the radius to be used for the AABB
},{key:"__getRadius",value:function __getRadius(){var dx=this.element.width()/2;var dy=this.element.height()/2;return Math.sqrt(dx*dx+dy*dy)}}]);return HtmlShape2d}(Shape2d);/*
    A simple 2d circle shape
    Author: Tar van Krieken
    Starting Date: 28/04/2018
*/var circlePrecision=5;var Circle2d=function(_Shape2d4){_inherits(Circle2d,_Shape2d4);function Circle2d(graphics,radius,color,preInit){_classCallCheck(this,Circle2d);var _this11=_possibleConstructorReturn(this,(Circle2d.__proto__||Object.getPrototypeOf(Circle2d)).call(this,graphics,color,preInit));_this11.setRadius(radius);return _this11}//the draw method
_createClass(Circle2d,[{key:"__redraw",value:function __redraw(){//draw the shape
this.gfx.clear();this.gfx.beginFill(this.color);this.gfx.drawCircle(0,0,circlePrecision);this.gfx.endFill();this.gfx.scale.set(this.getScale()*this.radius/circlePrecision);//setting the circle size by scaling in order to maintain quality for really small radii 
//setup the hitbox (used for interaction events)
this.gfx.hitArea=new PIXI.Circle(0,0,circlePrecision)}},{key:"setScale",value:function setScale(scale){_get(Circle2d.prototype.__proto__||Object.getPrototypeOf(Circle2d.prototype),"setScale",this).call(this,scale);this.gfx.scale.set(this.getScale()*this.radius/circlePrecision);return this}//the radius of the circle
},{key:"setRadius",value:function setRadius(radius){this.radius=radius;this.__redraw();this.__updateAABB();return this}},{key:"getRadius",value:function getRadius(){return this.radius}//the radius to be used for the AABB
},{key:"__getRadius",value:function __getRadius(){return this.radius}}]);return Circle2d}(Shape2d);/*
    Author: Mara Miulescu
    Date:   08/05/2018
*/var Line2d=function(_Shape2d5){_inherits(Line2d,_Shape2d5);function Line2d(graphics,startPoint,endPoint,width,color){_classCallCheck(this,Line2d);var _this12=_possibleConstructorReturn(this,(Line2d.__proto__||Object.getPrototypeOf(Line2d)).call(this,graphics,color));_this12.setWidth(width);_this12.startPoint=_this12.getLoc();_this12.endPoint=new XYZ(0,0,0);var This=_this12;_this12.startPoint.onChange(function(){This.__redraw()});_this12.getRot().onChange(function(){This.__redraw()});_this12.setStartPoint(startPoint);_this12.endPoint.onChange(function(){This.__redraw()});_this12.setEndPoint(endPoint);return _this12}//redraw method
_createClass(Line2d,[{key:"__redraw",value:function __redraw(){this.gfx.clear();this.gfx.lineStyle(this.width,this.color);this.gfx.moveTo(0,0);var delta=new Vec(this.endPoint).sub(this.getWorldLoc()).setZ(0);if(this.parentShape){//make delta relative to the offset ancestor
if(this.offsetShape)delta.add(this.offsetShape.getWorldLoc());//transform according to parent scale/angle
delta.div(this.parentShape.getWorldScale());delta.addAngle(-this.parentShape.getWorldAngle());if(this.offsetShape){//transform according to offset ancestor's scale/angle
delta.mul(this.offsetShape.getWorldScale());delta.addAngle(this.offsetShape.getWorldAngle())}}this.gfx.lineTo(delta.getX(),delta.getY());this.gfx.endFill()}// setters
},{key:"setWidth",value:function setWidth(width){this.width=width;this.__redraw();return this}},{key:"setStartPoint",value:function setStartPoint(startX,startY){this.startPoint.set(startX,startY);return this}},{key:"setEndPoint",value:function setEndPoint(endX,endY){this.endPoint.set(endX,endY);return this}},{key:"setOffsetAncestor",value:function setOffsetAncestor(shape){this.offsetShape=shape;return this}//getters
},{key:"getWidth",value:function getWidth(){return this.width}},{key:"getStartPoint",value:function getStartPoint(){return this.startPoint}},{key:"getEndPoint",value:function getEndPoint(){return this.endPoint}},{key:"getOffsetAncestor",value:function getOffsetAncestor(){return this.offsetShape}//redraw on scale change
},{key:"__triggerScaleChange",value:function __triggerScaleChange(){_get(Line2d.prototype.__proto__||Object.getPrototypeOf(Line2d.prototype),"__triggerScaleChange",this).call(this);this.__redraw()}}]);return Line2d}(Shape2d);/*
    Author: Mara Miulescu, Tar van Krieken
    Date:   24/05/2018
*/var TextShape2d=function(_Shape2d6){_inherits(TextShape2d,_Shape2d6);function TextShape2d(graphics,text,color,font,size,align){_classCallCheck(this,TextShape2d);var _this13=_possibleConstructorReturn(this,(TextShape2d.__proto__||Object.getPrototypeOf(TextShape2d)).call(this,graphics,color,function(){this.text=text;this.color=color;this.font=font;this.size=size;this.align=align}));var This=_this13;_this13.getLoc().onChange(function(){This.gfx.x-=0.5*This.gfx.width;This.gfx.y-=0.5*This.gfx.height});return _this13}_createClass(TextShape2d,[{key:"__createGfx",value:function __createGfx(){var data={fontFamily:"Arial",fontSize:24,fill:65280,align:"left"};if(this.font)data.fontFamily=this.font;// if ()
// if ()
// if ()
return new PIXI.Text(this.text,data)}},{key:"setColor",value:function setColor(color){if(color!=null){_get(TextShape2d.prototype.__proto__||Object.getPrototypeOf(TextShape2d.prototype),"setColor",this).call(this,color);this.gfx.style.fill=color}return this}}]);return TextShape2d}(Shape2d);/*
    Author: Mara Miulescu, Tar van Krieken
    Date:   24/05/2018
*/var ImageShape2d=function(_Shape2d7){_inherits(ImageShape2d,_Shape2d7);function ImageShape2d(graphics,source,width,height){_classCallCheck(this,ImageShape2d);var _this14=_possibleConstructorReturn(this,(ImageShape2d.__proto__||Object.getPrototypeOf(ImageShape2d)).call(this,graphics,null,function(){this.source=source}));_this14.setWidth(width);_this14.setHeight(height);var This=_this14;_this14.getLoc().onChange(function(){This.gfx.x-=0.5*This.gfx.width;This.gfx.y-=0.5*This.gfx.height});return _this14}_createClass(ImageShape2d,[{key:"__createGfx",value:function __createGfx(){return new PIXI.Sprite.from(this.source)}},{key:"setWidth",value:function setWidth(width){this.gfx.width=width;return this}},{key:"setHeight",value:function setHeight(height){this.gfx.height=height;return this}},{key:"getWidth",value:function getWidth(){return this.width}},{key:"getHeight",value:function getHeight(){return this.height}}]);return ImageShape2d}(Shape2d);/*
   Author: Mara Miulescu
   Date:   07/05/2018
*/var Rectangle2d=function(_Shape2d8){_inherits(Rectangle2d,_Shape2d8);function Rectangle2d(graphics,width,height,color){_classCallCheck(this,Rectangle2d);var _this15=_possibleConstructorReturn(this,(Rectangle2d.__proto__||Object.getPrototypeOf(Rectangle2d)).call(this,graphics,color));_this15.setWidth(width);_this15.setHeight(height);return _this15}_createClass(Rectangle2d,[{key:"__redraw",value:function __redraw(){this.gfx.clear();this.gfx.beginFill(this.color);this.gfx.drawRect(-0.5*this.width,-0.5*this.height,this.width,this.height);this.gfx.endFill();this.gfx.hitArea=new PIXI.Rectangle(-0.5*this.width,-0.5*this.height,this.width,this.height)}},{key:"setWidth",value:function setWidth(width){this.width=width;this.__redraw();return this}},{key:"setHeight",value:function setHeight(height){this.height=height;this.__redraw();return this}},{key:"getWidth",value:function getWidth(){return this.width}},{key:"getHeight",value:function getHeight(){return this.height}},{key:"__getRadius",value:function __getRadius(){// returns longest distance from center to a corner
return Math.sqrt(this.width*this.width+this.height*this.height)/2}}]);return Rectangle2d}(Shape2d);/*
   Author: Mara Miulescu
   Date:   07/05/2018
*/var RoundedRectangle2d=function(_Shape2d9){_inherits(RoundedRectangle2d,_Shape2d9);function RoundedRectangle2d(graphics,width,height,radius,color){_classCallCheck(this,RoundedRectangle2d);var _this16=_possibleConstructorReturn(this,(RoundedRectangle2d.__proto__||Object.getPrototypeOf(RoundedRectangle2d)).call(this,graphics,color));_this16.setWidth(width);_this16.setHeight(height);_this16.setRadius(radius);return _this16}_createClass(RoundedRectangle2d,[{key:"__redraw",value:function __redraw(){this.gfx.clear();this.gfx.beginFill(this.color);this.gfx.drawRoundedRect(-0.5*this.width,-0.5*this.height,this.width,this.height,this.radius);this.gfx.endFill();this.gfx.hitArea=new PIXI.RoundedRectangle(-0.5*this.width,-0.5*this.height,this.width,this.height,this.radius)}},{key:"setRadius",value:function setRadius(radius){this.radius=radius;this.__redraw();return this}},{key:"setWidth",value:function setWidth(width){this.width=width;this.__redraw();return this}},{key:"setHeight",value:function setHeight(height){this.height=height;this.__redraw();return this}},{key:"getWidth",value:function getWidth(){return this.width}},{key:"getHeight",value:function getHeight(){return this.height}},{key:"getRadius",value:function getRadius(){// returns radius of the rounded corners
return this.radius}},{key:"__getRadius",value:function __getRadius(){// returns longest distance from center to a corner
return(Math.sqrt((this.height-2*this.radius)*(this.height-2*this.radius)+(this.width-2*this.radius)*(this.width-2*this.radius))+2*this.radius)/2}}]);return RoundedRectangle2d}(Shape2d);/*
    Author: Mara Miulescu
    Date:   07/05/2018
*/var Polygon2d=function(_Shape2d10){_inherits(Polygon2d,_Shape2d10);function Polygon2d(graphics,points,color){_classCallCheck(this,Polygon2d);var _this17=_possibleConstructorReturn(this,(Polygon2d.__proto__||Object.getPrototypeOf(Polygon2d)).call(this,graphics,color));_this17.setPoints(points);return _this17}_createClass(Polygon2d,[{key:"__redraw",value:function __redraw(){this.gfx.clear();this.gfx.beginFill(this.color);this.gfx.drawPolygon(this.points);this.gfx.endFill();this.gfx.hitArea=new PIXI.Polygon(this.points)}// takes as argument an array of points ([x1,y1, x2,y2, x3, y3,..])
},{key:"setPoints",value:function setPoints(points){this.points=points;this.__redraw();return this}},{key:"getPoints",value:function getPoints(){return this.points}},{key:"__getPoints",value:function __getPoints(){return this.points}},{key:"__getRadius",value:function __getRadius(){var radius=0;for(var i=0;i<this.points.length-1;i+=2){var corner=new Vec(this.points[i],this.points[i+1],0);var dist=corner.getLength();if(dist>radius){radius=dist}}return radius}}]);return Polygon2d}(Shape2d);/*
   Author: Mara Miulescu
   Date:   07/05/2018
*/var Ellipse2d=function(_Shape2d11){_inherits(Ellipse2d,_Shape2d11);function Ellipse2d(graphics,width,height,color){_classCallCheck(this,Ellipse2d);var _this18=_possibleConstructorReturn(this,(Ellipse2d.__proto__||Object.getPrototypeOf(Ellipse2d)).call(this,graphics,color));_this18.setWidth(width);_this18.setHeight(height);return _this18}_createClass(Ellipse2d,[{key:"__redraw",value:function __redraw(){this.gfx.clear();this.gfx.beginFill(this.color);this.gfx.drawEllipse(-0.5*this.width,-0.5*this.height,this.width,this.height);this.gfx.hitArea=new PIXI.Ellipse(-0.5*this.width,-0.5*this.height,this.width,this.height)}},{key:"setWidth",value:function setWidth(width){this.width=width;this.__redraw();return this}},{key:"setHeight",value:function setHeight(height){this.height=height;this.__redraw();return this}},{key:"getWidth",value:function getWidth(){return this.width}},{key:"getHeight",value:function getHeight(){return this.height}},{key:"getRadius",value:function getRadius(){return this.radius}},{key:"__getRadius",value:function __getRadius(){// returns longest distance from center to a corner
if(this.width>=this.height){return this.width}return this.height}}]);return Ellipse2d}(Shape2d);/*
    2d Visualisation class
    Author: Tar van Krieken
    Starting Date: 08/05/2018
*/var Visualisation2d=function(_Graphics2d){_inherits(Visualisation2d,_Graphics2d);function Visualisation2d(container,tree,options,preInit){_classCallCheck(this,Visualisation2d);var _this19=_possibleConstructorReturn(this,(Visualisation2d.__proto__||Object.getPrototypeOf(Visualisation2d)).call(this,null,null,container,preInit));_this19.__setupVisualisation(tree,options);return _this19}//disposal, starts the removing of shapes, and removes the entire vis when done
_createClass(Visualisation2d,[{key:"destroy",value:function destroy(callback){this.__destroy(callback);_get(Visualisation2d.prototype.__proto__||Object.getPrototypeOf(Visualisation2d.prototype),"destroy",this).call(this)}//setup
},{key:"__setupRoot",value:function __setupRoot(){var node=this.tree.getRoot();var clas=this.__getNodeShapeClass(Visualisation2d.classes,node);var shape=new clas(this,node);return shape.add()}}]);return Visualisation2d}(Graphics2d);//copy methods of abstractVisualisation
var keys=Object.getOwnPropertyNames(AbstractVisualisation.prototype);for(var i=0;i<keys.length;i++){Visualisation2d.prototype[keys[i]]=AbstractVisualisation.prototype[keys[i]]}//make the visualisation system public
window.Visualisation2d=Visualisation2d;Visualisation2d.classes=window.VIZ2D={Visualisation:Visualisation2d,//general classes
XYZ:XYZ,Vec:Vec,//special shapes
Shape:Shape2d,CompoundShape:CompoundShape2d,ShapeGroup:ShapeGroup2d,NodeShape:NodeShape2d,HtmlShape:HtmlShape2d,//standard shapes
Circle:Circle2d,Line:Line2d,TextShape:TextShape2d,ImageShape:ImageShape2d,Rectangle:Rectangle2d,RoundedRectangle:RoundedRectangle2d,Polygon:Polygon2d,Ellipse:Ellipse2d};})();